/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../services/GrupoService';
import * as import4 from '../../services/user-data';
import * as import5 from './grupo';
import * as import6 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/di/injector';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/change_detection';
import * as import10 from '@angular/http/src/http';
import * as import11 from 'ionic-angular/util/events';
import * as import12 from '@ionic/storage/es2015/storage';
import * as import13 from 'ionic-angular/navigation/nav-controller';
import * as import14 from 'ionic-angular/navigation/nav-params';
import * as import15 from '@angular/core/src/metadata/view';
import * as import16 from '@angular/core/src/linker/component_factory';
import * as import17 from 'ionic-angular/components/toolbar/toolbar';
import * as import18 from 'ionic-angular/components/navbar/navbar';
import * as import19 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import20 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import21 from '@angular/core/src/linker/query_list';
import * as import22 from '@angular/common/src/directives/ng_if';
import * as import23 from 'ionic-angular/components/content/content';
import * as import24 from '@angular/forms/src/directives/ng_model';
import * as import25 from '@angular/forms/src/directives/ng_control_status';
import * as import26 from 'ionic-angular/components/segment/segment';
import * as import27 from '@angular/common/src/directives/ng_switch';
import * as import28 from 'ionic-angular/config/config';
import * as import29 from '@angular/core/src/linker/element_ref';
import * as import30 from 'ionic-angular/navigation/view-controller';
import * as import31 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import32 from 'ionic-angular/components/app/app';
import * as import33 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import34 from '@angular/core/src/linker/template_ref';
import * as import35 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import36 from 'ionic-angular/util/keyboard';
import * as import37 from '@angular/core/src/zone/ng_zone';
import * as import38 from 'ionic-angular/components/tabs/tabs';
import * as import39 from '../../node_modules/ionic-angular/components/segment/segment.ngfactory';
import * as import40 from '@angular/forms/src/directives/ng_control';
import * as import41 from 'ionic-angular/components/button/button';
import * as import42 from 'ionic-angular/components/icon/icon';
import * as import43 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import44 from '@angular/common/src/directives/ng_for';
import * as import45 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import46 from 'ionic-angular/components/list/list';
import * as import47 from 'ionic-angular/gestures/gesture-controller';
import * as import48 from 'ionic-angular/components/item/item';
import * as import49 from 'ionic-angular/components/label/label';
import * as import50 from 'ionic-angular/components/avatar/avatar';
import * as import51 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import52 from 'ionic-angular/util/form';
import * as import53 from '@angular/core/src/security';
import * as import54 from 'ionic-angular/components/note/note';
var renderType_GrupoPage_Host:import0.RenderComponentType = (null as any);
class _View_GrupoPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _GrupoService_0_4:import3.GrupoService;
  _UserData_0_5:import4.UserData;
  _GrupoPage_0_6:import5.GrupoPage;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GrupoPage_Host0,renderType_GrupoPage_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_GrupoPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._GrupoService_0_4 = new import3.GrupoService(this.parentInjector.get(import10.Http));
    this._UserData_0_5 = new import4.UserData(this.parentInjector.get(import11.Events),this.parentInjector.get(import12.Storage));
    this._GrupoPage_0_6 = new import5.GrupoPage(this.parentInjector.get(import13.NavController),this.parentInjector.get(import14.NavParams),this._GrupoService_0_4,this._UserData_0_5);
    this._appEl_0.initComponent(this._GrupoPage_0_6,[],compView_0);
    compView_0.create(this._GrupoPage_0_6,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.GrupoService) && (0 === requestNodeIndex))) { return this._GrupoService_0_4; }
    if (((token === import4.UserData) && (0 === requestNodeIndex))) { return this._UserData_0_5; }
    if (((token === import5.GrupoPage) && (0 === requestNodeIndex))) { return this._GrupoPage_0_6; }
    return notFoundResult;
  }
}
function viewFactory_GrupoPage_Host0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_GrupoPage_Host === (null as any))) { (renderType_GrupoPage_Host = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,[],{})); }
  return new _View_GrupoPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const GrupoPageNgFactory:import16.ComponentFactory<import5.GrupoPage> = new import16.ComponentFactory<import5.GrupoPage>('ng-component',viewFactory_GrupoPage_Host0,import5.GrupoPage);
const styles_GrupoPage:any[] = [];
var renderType_GrupoPage:import0.RenderComponentType = (null as any);
class _View_GrupoPage0 extends import1.AppView<import5.GrupoPage> {
  _el_0:any;
  _Header_0_3:import17.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import18.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import19.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _ToolbarItem_7_3:import20.ToolbarItem;
  _query_Button_7_0:import21.QueryList<any>;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _TemplateRef_9_5:any;
  _NgIf_9_6:import22.NgIf;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _Content_14_4:import23.Content;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _NgModel_18_3:import24.NgModel;
  _NgControl_18_4:any;
  _NgControlStatus_18_5:import25.NgControlStatus;
  _Segment_18_6:import26.Segment;
  _query_SegmentButton_18_0:import21.QueryList<any>;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _SegmentButton_20_4:import26.SegmentButton;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _SegmentButton_23_4:import26.SegmentButton;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _NgSwitch_28_3:import27.NgSwitch;
  _text_29:any;
  _anchor_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _TemplateRef_30_5:any;
  _NgSwitchCase_30_6:import27.NgSwitchCase;
  _text_31:any;
  _anchor_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _TemplateRef_32_5:any;
  _NgSwitchCase_32_6:import27.NgSwitchCase;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GrupoPage0,renderType_GrupoPage,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import17.Header(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import30.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import31.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import18.Navbar(this.parentInjector.get(import32.App),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import13.NavController,(null as any)),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import33.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import19.ToolbarTitle(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import17.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_7,'end','');
    this._ToolbarItem_7_3 = new import20.ToolbarItem(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_7),this.renderer,this.parentInjector.get(import17.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_7_0 = new import21.QueryList<any>();
    this._text_8 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._appEl_9 = new import2.AppElement(9,7,this,this._anchor_9);
    this._TemplateRef_9_5 = new import34.TemplateRef_(this._appEl_9,viewFactory_GrupoPage1);
    this._NgIf_9_6 = new import22.NgIf(this._appEl_9.vcRef,this._TemplateRef_9_5);
    this._text_10 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [].concat([this._el_7]),
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','bg-branco');
    this.renderer.setElementAttribute(this._el_14,'padding','');
    this._appEl_14 = new import2.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import35.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import23.Content(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import32.App),this.parentInjector.get(import36.Keyboard),this.parentInjector.get(import37.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import38.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4,[],compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'ion-segment',(null as any));
    this._NgModel_18_3 = new import24.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_18_4 = this._NgModel_18_3;
    this._NgControlStatus_18_5 = new import25.NgControlStatus(this._NgControl_18_4);
    this._Segment_18_6 = new import26.Segment(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_18),this.renderer,this._NgControl_18_4);
    this._query_SegmentButton_18_0 = new import21.QueryList<any>();
    this._text_19 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','segment-button');
    this.renderer.setElementAttribute(this._el_20,'role','button');
    this.renderer.setElementAttribute(this._el_20,'tappable','');
    this.renderer.setElementAttribute(this._el_20,'value','eventos');
    this._appEl_20 = new import2.AppElement(20,18,this,this._el_20);
    var compView_20:any = import39.viewFactory_SegmentButton0(this.viewUtils,this.injector(20),this._appEl_20);
    this._SegmentButton_20_4 = new import26.SegmentButton(this.renderer,new import29.ElementRef(this._el_20));
    this._appEl_20.initComponent(this._SegmentButton_20_4,[],compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n        Eventos\n      ',(null as any));
    compView_20.create(this._SegmentButton_20_4,[[].concat([this._text_21])],(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_18,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','segment-button');
    this.renderer.setElementAttribute(this._el_23,'role','button');
    this.renderer.setElementAttribute(this._el_23,'tappable','');
    this.renderer.setElementAttribute(this._el_23,'value','participantes');
    this._appEl_23 = new import2.AppElement(23,18,this,this._el_23);
    var compView_23:any = import39.viewFactory_SegmentButton0(this.viewUtils,this.injector(23),this._appEl_23);
    this._SegmentButton_23_4 = new import26.SegmentButton(this.renderer,new import29.ElementRef(this._el_23));
    this._appEl_23.initComponent(this._SegmentButton_23_4,[],compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n        Participantes\n      ',(null as any));
    compView_23.create(this._SegmentButton_23_4,[[].concat([this._text_24])],(null as any));
    this._text_25 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._text_26 = this.renderer.createText(this._el_16,'\n  ',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'div',(null as any));
    this._NgSwitch_28_3 = new import27.NgSwitch();
    this._text_29 = this.renderer.createText(this._el_28,'\n    ',(null as any));
    this._anchor_30 = this.renderer.createTemplateAnchor(this._el_28,(null as any));
    this._appEl_30 = new import2.AppElement(30,28,this,this._anchor_30);
    this._TemplateRef_30_5 = new import34.TemplateRef_(this._appEl_30,viewFactory_GrupoPage2);
    this._NgSwitchCase_30_6 = new import27.NgSwitchCase(this._appEl_30.vcRef,this._TemplateRef_30_5,this._NgSwitch_28_3);
    this._text_31 = this.renderer.createText(this._el_28,'\n\n    ',(null as any));
    this._anchor_32 = this.renderer.createTemplateAnchor(this._el_28,(null as any));
    this._appEl_32 = new import2.AppElement(32,28,this,this._anchor_32);
    this._TemplateRef_32_5 = new import34.TemplateRef_(this._appEl_32,viewFactory_GrupoPage5);
    this._NgSwitchCase_32_6 = new import27.NgSwitchCase(this._appEl_32.vcRef,this._TemplateRef_32_5,this._NgSwitch_28_3);
    this._text_33 = this.renderer.createText(this._el_28,'\n\n  ',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_14.create(this._Content_14_4,[
      [],
      [].concat([
        this._text_15,
        this._el_16,
        this._text_27,
        this._el_28,
        this._text_34
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_35 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import9.UNINITIALIZED;
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    this._expr_3 = import9.UNINITIALIZED;
    this._expr_4 = import9.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_18,'ngModelChange',this.eventHandler(this._handle_ngModelChange_18_0.bind(this)));
    this._expr_6 = import9.UNINITIALIZED;
    const subscription_0:any = this._NgModel_18_3.update.subscribe(this.eventHandler(this._handle_ngModelChange_18_0.bind(this)));
    this._expr_7 = import9.UNINITIALIZED;
    this._expr_8 = import9.UNINITIALIZED;
    this._expr_9 = import9.UNINITIALIZED;
    this._expr_10 = import9.UNINITIALIZED;
    this._expr_11 = import9.UNINITIALIZED;
    this._expr_12 = import9.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_20,'click',this.eventHandler(this._handle_click_20_0.bind(this)));
    this._expr_14 = import9.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_23,'click',this.eventHandler(this._handle_click_23_0.bind(this)));
    this._expr_16 = import9.UNINITIALIZED;
    this._expr_17 = import9.UNINITIALIZED;
    this._expr_18 = import9.UNINITIALIZED;
    this._expr_19 = import9.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._anchor_30,
      this._text_31,
      this._anchor_32,
      this._text_33,
      this._text_34,
      this._text_35
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import34.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import22.NgIf) && (9 === requestNodeIndex))) { return this._NgIf_9_6; }
    if (((token === import20.ToolbarItem) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarItem_7_3; }
    if (((token === import18.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4; }
    if (((token === import17.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3; }
    if (((token === import26.SegmentButton) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._SegmentButton_20_4; }
    if (((token === import26.SegmentButton) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._SegmentButton_23_4; }
    if (((token === import24.NgModel) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._NgModel_18_3; }
    if (((token === import40.NgControl) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._NgControl_18_4; }
    if (((token === import25.NgControlStatus) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._NgControlStatus_18_5; }
    if (((token === import26.Segment) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Segment_18_6; }
    if (((token === import34.TemplateRef) && (30 === requestNodeIndex))) { return this._TemplateRef_30_5; }
    if (((token === import27.NgSwitchCase) && (30 === requestNodeIndex))) { return this._NgSwitchCase_30_6; }
    if (((token === import34.TemplateRef) && (32 === requestNodeIndex))) { return this._TemplateRef_32_5; }
    if (((token === import27.NgSwitchCase) && (32 === requestNodeIndex))) { return this._NgSwitchCase_32_6; }
    if (((token === import27.NgSwitch) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._NgSwitch_28_3; }
    if (((token === import23.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Content_14_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import9.SimpleChange} = (null as any);
    const currVal_3:any = this.context.isAdmin;
    if (import6.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_9_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_14_4.ngOnInit(); }
    changes = (null as any);
    const currVal_6:any = this.context.segGrupo;
    if (import6.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgModel_18_3.model = currVal_6;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import9.SimpleChange(this._expr_6,currVal_6);
      this._expr_6 = currVal_6;
    }
    if ((changes !== (null as any))) { this._NgModel_18_3.ngOnChanges(changes); }
    const currVal_14:any = 'eventos';
    if (import6.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._SegmentButton_20_4.value = currVal_14;
      this._expr_14 = currVal_14;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_20_4.ngOnInit(); }
    const currVal_16:any = 'participantes';
    if (import6.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._SegmentButton_23_4.value = currVal_16;
      this._expr_16 = currVal_16;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_23_4.ngOnInit(); }
    const currVal_17:any = this.context.segGrupo;
    if (import6.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._NgSwitch_28_3.ngSwitch = currVal_17;
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = 'eventos';
    if (import6.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._NgSwitchCase_30_6.ngSwitchCase = currVal_18;
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = 'participantes';
    if (import6.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._NgSwitchCase_32_6.ngSwitchCase = currVal_19;
      this._expr_19 = currVal_19;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_7_0.dirty) {
          this._query_Button_7_0.reset([this._appEl_9.mapNestedViews(_View_GrupoPage1,(nestedView:_View_GrupoPage1):any => {
            return [nestedView._Button_0_4];
        })]);
        this._ToolbarItem_7_3._buttons = this._query_Button_7_0;
        this._query_Button_7_0.notifyOnChanges();
      }
      if (this._query_SegmentButton_18_0.dirty) {
        this._query_SegmentButton_18_0.reset([
          this._SegmentButton_20_4,
          this._SegmentButton_23_4
        ]
        );
        this._Segment_18_6._buttons = this._query_SegmentButton_18_0;
        this._query_SegmentButton_18_0.notifyOnChanges();
      }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import6.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import6.interpolate(1,'',this.context.nome,'');
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_5,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = this._Content_14_4._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = this._NgControlStatus_18_5.ngClassUntouched;
    if (import6.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_18,'ng-untouched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_18_5.ngClassTouched;
    if (import6.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_18,'ng-touched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_18_5.ngClassPristine;
    if (import6.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_18,'ng-pristine',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_18_5.ngClassDirty;
    if (import6.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_18,'ng-dirty',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_18_5.ngClassValid;
    if (import6.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_18,'ng-valid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_18_5.ngClassInvalid;
    if (import6.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_18,'ng-invalid',currVal_12);
      this._expr_12 = currVal_12;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Segment_18_6.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._NgModel_18_3.ngOnDestroy();
    this._Content_14_4.ngOnDestroy();
  }
  private _handle_ngModelChange_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.segGrupo = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_20_0($event:any):boolean {
    this._appEl_20.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_20_4.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_23_0($event:any):boolean {
    this._appEl_23.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_23_4.onClick()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_GrupoPage0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<import5.GrupoPage> {
  if ((renderType_GrupoPage === (null as any))) { (renderType_GrupoPage = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,styles_GrupoPage,{})); }
  return new _View_GrupoPage0(viewUtils,parentInjector,declarationEl);
}
class _View_GrupoPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Button_0_4:import41.Button;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import42.Icon;
  _text_3:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GrupoPage1,renderType_GrupoPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import43.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import41.Button((null as any),'',this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Button_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'name','brush');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import42.Icon(this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_0.create(this._Button_0_4,[[].concat([
        this._text_1,
        this._el_2,
        this._text_3
      ]
    )],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import42.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3; }
    if (((token === import41.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Button_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = 'brush';
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Icon_2_3.name = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.ngAfterContentInit(); } }
    const currVal_2:any = this._Icon_2_3._hidden;
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_GrupoPage0>this.parent)._query_Button_7_0.setDirty();
  }
  destroyInternal():void {
    this._Icon_2_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.editarGrupo()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_GrupoPage1(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GrupoPage1(viewUtils,parentInjector,declarationEl);
}
class _View_GrupoPage2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import22.NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgFor_4_6:import44.NgFor;
  _text_5:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GrupoPage2,renderType_GrupoPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import34.TemplateRef_(this._appEl_2,viewFactory_GrupoPage3);
    this._NgIf_2_6 = new import22.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_4 = new import2.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import34.TemplateRef_(this._appEl_4,viewFactory_GrupoPage4);
    this._NgFor_4_6 = new import44.NgFor(this._appEl_4.vcRef,this._TemplateRef_4_5,this.parent.parentInjector.get(import45.IterableDiffers),this.parent.ref);
    this._text_5 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._expr_0 = import9.UNINITIALIZED;
    this._expr_1 = import9.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import22.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import34.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import44.NgFor) && (4 === requestNodeIndex))) { return this._NgFor_4_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import9.SimpleChange} = (null as any);
    const currVal_0:any = this.parent.context.isAdmin;
    if (import6.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    changes = (null as any);
    const currVal_1:any = this.parent.context.eventosGrupo;
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgFor_4_6.ngForOf = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import9.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._NgFor_4_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_4_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_GrupoPage2(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GrupoPage2(viewUtils,parentInjector,declarationEl);
}
class _View_GrupoPage3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Button_2_4:import41.Button;
  _el_3:any;
  _Icon_3_3:import42.Icon;
  _text_4:any;
  _text_5:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GrupoPage3,renderType_GrupoPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','botaoCriarGrupo');
    this.renderer.setElementAttribute(this._el_2,'full','');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this.renderer.setElementAttribute(this._el_2,'style','margin-top: 20px;');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import43.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import41.Button((null as any),'',this.parent.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4,[],compView_2);
    this._el_3 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_3,'name','person-add');
    this.renderer.setElementAttribute(this._el_3,'role','img');
    this._Icon_3_3 = new import42.Icon(this.parent.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_3),this.renderer);
    this._text_4 = this.renderer.createText((null as any),'Criar Evento',(null as any));
      compView_2.create(this._Button_2_4,[[].concat([
        this._el_3,
        this._text_4
      ]
    )],(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    this._expr_3 = import9.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._text_5
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import42.Icon) && (3 === requestNodeIndex))) { return this._Icon_3_3; }
    if (((token === import41.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Button_2_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = '';
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_2_4.full = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    if (changed) { this._appEl_2.componentView.markAsCheckOnce(); }
    const currVal_2:any = 'person-add';
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Icon_3_3.name = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.ngAfterContentInit(); } }
    const currVal_3:any = this._Icon_3_3._hidden;
    if (import6.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_3,'hide',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_3_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.cadastrarEvento()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_GrupoPage3(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GrupoPage3(viewUtils,parentInjector,declarationEl);
}
class _View_GrupoPage4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GrupoPage4,renderType_GrupoPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','modeloItemAgenda1');
    this._text_3 = this.renderer.createText(this._el_2,'\n\n          ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','modeloItemAgenda-data');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'h4',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n\n          ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','modeloItemAgenda-nomeEvento');
    this._text_14 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'p',(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n          ',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n\n          ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','modeloItemAgenda-horario');
    this._text_20 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'p',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'\n          ',(null as any));
    this._text_24 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    this._expr_3 = import9.UNINITIALIZED;
    this._expr_4 = import9.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import6.interpolate(1,'',this.context.$implicit.momento.date(),'');
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_7,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import6.interpolate(1,'',this.context.$implicit.momento.format('dddd'),'');
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_10,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import6.interpolate(1,'',this.context.$implicit.titulo,'');
    if (import6.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_16,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import6.interpolate(2,'',this.context.$implicit.hrInicial,' às ',this.context.$implicit.hrFinal,'');
    if (import6.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_22,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.abrirEvento(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_GrupoPage4(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GrupoPage4(viewUtils,parentInjector,declarationEl);
}
class _View_GrupoPage5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import22.NgIf;
  _text_3:any;
  _el_4:any;
  _List_4_3:import46.List;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgFor_6_6:import44.NgFor;
  _text_7:any;
  _text_8:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GrupoPage5,renderType_GrupoPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import34.TemplateRef_(this._appEl_2,viewFactory_GrupoPage6);
    this._NgIf_2_6 = new import22.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'ion-list',(null as any));
    this._List_4_3 = new import46.List(this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_4),this.renderer,this.parent.parentInjector.get(import47.GestureController));
    this._text_5 = this.renderer.createText(this._el_4,'\n\n          ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._appEl_6 = new import2.AppElement(6,4,this,this._anchor_6);
    this._TemplateRef_6_5 = new import34.TemplateRef_(this._appEl_6,viewFactory_GrupoPage7);
    this._NgFor_6_6 = new import44.NgFor(this._appEl_6.vcRef,this._TemplateRef_6_5,this.parent.parentInjector.get(import45.IterableDiffers),this.parent.ref);
    this._text_7 = this.renderer.createText(this._el_4,'\n\n        ',(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._expr_0 = import9.UNINITIALIZED;
    this._expr_1 = import9.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._text_8
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import22.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import34.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import44.NgFor) && (6 === requestNodeIndex))) { return this._NgFor_6_6; }
    if (((token === import46.List) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._List_4_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import9.SimpleChange} = (null as any);
    const currVal_0:any = this.parent.context.isAdmin;
    if (import6.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    changes = (null as any);
    const currVal_1:any = this.parent.context.listaUsuarios;
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgFor_6_6.ngForOf = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import9.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._NgFor_6_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_6_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_GrupoPage5(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GrupoPage5(viewUtils,parentInjector,declarationEl);
}
class _View_GrupoPage6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Button_2_4:import41.Button;
  _el_3:any;
  _Icon_3_3:import42.Icon;
  _text_4:any;
  _text_5:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GrupoPage6,renderType_GrupoPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','botaoCriarGrupo');
    this.renderer.setElementAttribute(this._el_2,'full','');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this.renderer.setElementAttribute(this._el_2,'style','margin-top: 20px;');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import43.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import41.Button((null as any),'',this.parent.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4,[],compView_2);
    this._el_3 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_3,'name','person-add');
    this.renderer.setElementAttribute(this._el_3,'role','img');
    this._Icon_3_3 = new import42.Icon(this.parent.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_3),this.renderer);
    this._text_4 = this.renderer.createText((null as any),'adicionar participante',(null as any));
      compView_2.create(this._Button_2_4,[[].concat([
        this._el_3,
        this._text_4
      ]
    )],(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    this._expr_3 = import9.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._text_5
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import42.Icon) && (3 === requestNodeIndex))) { return this._Icon_3_3; }
    if (((token === import41.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Button_2_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = '';
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_2_4.full = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    if (changed) { this._appEl_2.componentView.markAsCheckOnce(); }
    const currVal_2:any = 'person-add';
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Icon_3_3.name = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.ngAfterContentInit(); } }
    const currVal_3:any = this._Icon_3_3._hidden;
    if (import6.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_3,'hide',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_3_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.criarGrupo()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_GrupoPage6(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GrupoPage6(viewUtils,parentInjector,declarationEl);
}
class _View_GrupoPage7 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import48.Item;
  _ItemContent_0_5:import48.ItemContent;
  _query_Label_0_0:import21.QueryList<any>;
  _query_Button_0_1:import21.QueryList<any>;
  _query_Icon_0_2:import21.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Label_2_3:import49.Label;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _Avatar_5_3:import50.Avatar;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _appEl_7:import2.AppElement;
  _TemplateRef_7_5:any;
  _NgIf_7_6:import22.NgIf;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _TemplateRef_9_5:any;
  _NgIf_9_6:import22.NgIf;
  _text_10:any;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _TemplateRef_12_5:any;
  _NgIf_12_6:import22.NgIf;
  _text_13:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GrupoPage7,renderType_GrupoPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import51.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import48.Item(this.parent.parent.parentInjector.get(import52.Form),this.parent.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import48.ItemContent();
    this._query_Label_0_0 = new import21.QueryList<any>();
    this._query_Button_0_1 = new import21.QueryList<any>();
    this._query_Icon_0_2 = new import21.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_2_3 = new import49.Label(this.parent.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_2),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_5,'item-left','');
    this._Avatar_5_3 = new import50.Avatar();
    this._text_6 = this.renderer.createText(this._el_5,'\n              ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor(this._el_5,(null as any));
    this._appEl_7 = new import2.AppElement(7,5,this,this._anchor_7);
    this._TemplateRef_7_5 = new import34.TemplateRef_(this._appEl_7,viewFactory_GrupoPage8);
    this._NgIf_7_6 = new import22.NgIf(this._appEl_7.vcRef,this._TemplateRef_7_5);
    this._text_8 = this.renderer.createText(this._el_5,'\n              ',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_5,(null as any));
    this._appEl_9 = new import2.AppElement(9,5,this,this._anchor_9);
    this._TemplateRef_9_5 = new import34.TemplateRef_(this._appEl_9,viewFactory_GrupoPage9);
    this._NgIf_9_6 = new import22.NgIf(this._appEl_9.vcRef,this._TemplateRef_9_5);
    this._text_10 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_12 = new import2.AppElement(12,0,this,this._anchor_12);
    this._TemplateRef_12_5 = new import34.TemplateRef_(this._appEl_12,viewFactory_GrupoPage10);
    this._NgIf_12_6 = new import22.NgIf(this._appEl_12.vcRef,this._TemplateRef_12_5);
    this._text_13 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._query_Label_0_0.reset([this._Label_2_3]);
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      [].concat([this._el_5]),
      [].concat([this._el_2]),
      [].concat([
        this._text_1,
        this._text_4,
        this._text_11,
        this._text_13
      ]
      ),
      [],
      [].concat([this._appEl_12])
    ]
    ,(null as any));
    this._expr_0 = import9.UNINITIALIZED;
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    this._expr_3 = import9.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._text_11,
      this._anchor_12,
      this._text_13
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import49.Label) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Label_2_3; }
    if (((token === import34.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import22.NgIf) && (7 === requestNodeIndex))) { return this._NgIf_7_6; }
    if (((token === import34.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import22.NgIf) && (9 === requestNodeIndex))) { return this._NgIf_9_6; }
    if (((token === import50.Avatar) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Avatar_5_3; }
    if (((token === import34.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import22.NgIf) && (12 === requestNodeIndex))) { return this._NgIf_12_6; }
    if (((token === import48.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Item_0_4; }
    if (((token === import48.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ItemContent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = (this.context.$implicit.fotoProfile != (null as any));
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_7_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = (this.context.$implicit.fotoProfile == (null as any));
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_9_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = (this.context.$implicit.id == this.parent.parent.context.adminGrupo.id);
    if (import6.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_12_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset([]);
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_0:any = import6.interpolate(1,'',this.context.$implicit.username,'');
    if (import6.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_GrupoPage7(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GrupoPage7(viewUtils,parentInjector,declarationEl);
}
class _View_GrupoPage8 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GrupoPage8,renderType_GrupoPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this._expr_0 = import9.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import6.interpolate(1,'',this.parent.context.$implicit.fotoProfile,'');
    if (import6.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import53.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_GrupoPage8(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GrupoPage8(viewUtils,parentInjector,declarationEl);
}
class _View_GrupoPage9 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GrupoPage9,renderType_GrupoPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'src','http://www.iconsfind.com/wp-content/uploads/2015/11/20151112_5643f331cf8c4.png');
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
}
function viewFactory_GrupoPage9(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GrupoPage9(viewUtils,parentInjector,declarationEl);
}
class _View_GrupoPage10 extends import1.AppView<any> {
  _el_0:any;
  _Note_0_3:import54.Note;
  _text_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_GrupoPage10,renderType_GrupoPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-note',(null as any));
    this.renderer.setElementAttribute(this._el_0,'item-right','');
    this._Note_0_3 = new import54.Note();
    this._text_1 = this.renderer.createText(this._el_0,'\n             admin\n            ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import54.Note) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Note_0_3; }
    return notFoundResult;
  }
}
function viewFactory_GrupoPage10(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_GrupoPage10(viewUtils,parentInjector,declarationEl);
}