/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../services/UsuarioService';
import * as import4 from './cadastrar-grupo';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/http/src/http';
import * as import10 from 'ionic-angular/navigation/nav-controller';
import * as import11 from 'ionic-angular/navigation/nav-params';
import * as import12 from 'ionic-angular/components/loading/loading';
import * as import13 from 'ionic-angular/components/toast/toast';
import * as import14 from '@angular/core/src/metadata/view';
import * as import15 from '@angular/core/src/linker/component_factory';
import * as import16 from 'ionic-angular/components/toolbar/toolbar';
import * as import17 from 'ionic-angular/components/navbar/navbar';
import * as import18 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import19 from 'ionic-angular/components/content/content';
import * as import20 from '@angular/forms/src/directives/ng_form';
import * as import21 from '@angular/forms/src/directives/ng_control_status';
import * as import22 from 'ionic-angular/components/item/item';
import * as import23 from '@angular/core/src/linker/query_list';
import * as import24 from 'ionic-angular/components/label/label';
import * as import25 from '@angular/forms/src/directives/validators';
import * as import26 from '@angular/forms/src/directives/ng_model';
import * as import27 from 'ionic-angular/components/input/input';
import * as import28 from 'ionic-angular/components/button/button';
import * as import29 from 'ionic-angular/components/icon/icon';
import * as import30 from 'ionic-angular/config/config';
import * as import31 from '@angular/core/src/linker/element_ref';
import * as import32 from 'ionic-angular/navigation/view-controller';
import * as import33 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import34 from 'ionic-angular/components/app/app';
import * as import35 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import36 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import37 from 'ionic-angular/util/keyboard';
import * as import38 from '@angular/core/src/zone/ng_zone';
import * as import39 from 'ionic-angular/components/tabs/tabs';
import * as import40 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import41 from 'ionic-angular/util/form';
import * as import42 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import43 from 'ionic-angular/platform/platform';
import * as import44 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import45 from '@angular/forms/src/validators';
import * as import46 from '@angular/forms/src/directives/ng_control';
import * as import47 from '@angular/forms/src/directives/control_container';
var renderType_CadastrarGrupoPage_Host:import0.RenderComponentType = (null as any);
class _View_CadastrarGrupoPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UsuarioService_0_4:import3.UsuarioService;
  _CadastrarGrupoPage_0_5:import4.CadastrarGrupoPage;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_CadastrarGrupoPage_Host0,renderType_CadastrarGrupoPage_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_CadastrarGrupoPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UsuarioService_0_4 = new import3.UsuarioService(this.parentInjector.get(import9.Http));
    this._CadastrarGrupoPage_0_5 = new import4.CadastrarGrupoPage(this.parentInjector.get(import10.NavController),this._UsuarioService_0_4,this.parentInjector.get(import11.NavParams),this.parentInjector.get(import12.LoadingController),this.parentInjector.get(import13.ToastController));
    this._appEl_0.initComponent(this._CadastrarGrupoPage_0_5,[],compView_0);
    compView_0.create(this._CadastrarGrupoPage_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.UsuarioService) && (0 === requestNodeIndex))) { return this._UsuarioService_0_4; }
    if (((token === import4.CadastrarGrupoPage) && (0 === requestNodeIndex))) { return this._CadastrarGrupoPage_0_5; }
    return notFoundResult;
  }
}
function viewFactory_CadastrarGrupoPage_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_CadastrarGrupoPage_Host === (null as any))) { (renderType_CadastrarGrupoPage_Host = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,[],{})); }
  return new _View_CadastrarGrupoPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const CadastrarGrupoPageNgFactory:import15.ComponentFactory<import4.CadastrarGrupoPage> = new import15.ComponentFactory<import4.CadastrarGrupoPage>('ng-component',viewFactory_CadastrarGrupoPage_Host0,import4.CadastrarGrupoPage);
const styles_CadastrarGrupoPage:any[] = [];
var renderType_CadastrarGrupoPage:import0.RenderComponentType = (null as any);
class _View_CadastrarGrupoPage0 extends import1.AppView<import4.CadastrarGrupoPage> {
  _el_0:any;
  _Header_0_3:import16.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import17.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import18.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import19.Content;
  _text_10:any;
  _el_11:any;
  _NgForm_11_3:import20.NgForm;
  _ControlContainer_11_4:any;
  _NgControlStatusGroup_11_5:import21.NgControlStatusGroup;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _Item_13_4:import22.Item;
  _ItemContent_13_5:import22.ItemContent;
  _query_Label_13_0:import23.QueryList<any>;
  _query_Button_13_1:import23.QueryList<any>;
  _query_Icon_13_2:import23.QueryList<any>;
  _text_14:any;
  _el_15:any;
  _Label_15_3:import24.Label;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _RequiredValidator_18_4:import25.RequiredValidator;
  _NG_VALIDATORS_18_5:any[];
  _NgModel_18_6:import26.NgModel;
  _NgControl_18_7:any;
  _NgControlStatus_18_8:import21.NgControlStatus;
  _TextInput_18_9:import27.TextInput;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _Item_21_4:import22.Item;
  _ItemContent_21_5:import22.ItemContent;
  _query_Label_21_0:import23.QueryList<any>;
  _query_Button_21_1:import23.QueryList<any>;
  _query_Icon_21_2:import23.QueryList<any>;
  _text_22:any;
  _el_23:any;
  _Label_23_3:import24.Label;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _RequiredValidator_26_4:import25.RequiredValidator;
  _NG_VALIDATORS_26_5:any[];
  _NgModel_26_6:import26.NgModel;
  _NgControl_26_7:any;
  _NgControlStatus_26_8:import21.NgControlStatus;
  _TextArea_26_9:import27.TextArea;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import2.AppElement;
  _Button_29_4:import28.Button;
  _text_30:any;
  _el_31:any;
  _Icon_31_3:import29.Icon;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_CadastrarGrupoPage0,renderType_CadastrarGrupoPage,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import16.Header(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import32.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import33.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import17.Navbar(this.parentInjector.get(import34.App),this.parentInjector.get(import32.ViewController,(null as any)),this.parentInjector.get(import10.NavController,(null as any)),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import35.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import18.ToolbarTitle(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import16.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'Cadastrar Grupo',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','cadastrar-evento bg-branco');
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import36.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import19.Content(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import34.App),this.parentInjector.get(import37.Keyboard),this.parentInjector.get(import38.NgZone),this.parentInjector.get(import32.ViewController,(null as any)),this.parentInjector.get(import39.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'form',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','formCadastrarEvento');
    this.renderer.setElementAttribute(this._el_11,'novalidate','');
    this._NgForm_11_3 = new import20.NgForm((null as any),(null as any));
    this._ControlContainer_11_4 = this._NgForm_11_3;
    this._NgControlStatusGroup_11_5 = new import21.NgControlStatusGroup(this._ControlContainer_11_4);
    this._text_12 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','itemCadastrarEvento item item-block');
    this._appEl_13 = new import2.AppElement(13,11,this,this._el_13);
    var compView_13:any = import40.viewFactory_Item0(this.viewUtils,this.injector(13),this._appEl_13);
    this._Item_13_4 = new import22.Item(this.parentInjector.get(import41.Form),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_13),this.renderer);
    this._ItemContent_13_5 = new import22.ItemContent();
    this._query_Label_13_0 = new import23.QueryList<any>();
    this._query_Button_13_1 = new import23.QueryList<any>();
    this._query_Icon_13_2 = new import23.QueryList<any>();
    this._appEl_13.initComponent(this._Item_13_4,[],compView_13);
    this._text_14 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','labelCadastrarEvento');
    this.renderer.setElementAttribute(this._el_15,'stacked','');
    this._Label_15_3 = new import24.Label(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_15),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Nome do Grupo',(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_18,'name','nome');
    this.renderer.setElementAttribute(this._el_18,'ngModel','');
    this.renderer.setElementAttribute(this._el_18,'required','');
    this.renderer.setElementAttribute(this._el_18,'type','text');
    this._appEl_18 = new import2.AppElement(18,13,this,this._el_18);
    var compView_18:any = import42.viewFactory_TextInput0(this.viewUtils,this.injector(18),this._appEl_18);
    this._RequiredValidator_18_4 = new import25.RequiredValidator();
    this._NG_VALIDATORS_18_5 = [this._RequiredValidator_18_4];
    this._NgModel_18_6 = new import26.NgModel(this._ControlContainer_11_4,this._NG_VALIDATORS_18_5,(null as any),(null as any));
    this._NgControl_18_7 = this._NgModel_18_6;
    this._NgControlStatus_18_8 = new import21.NgControlStatus(this._NgControl_18_7);
    this._TextInput_18_9 = new import27.TextInput(this.parentInjector.get(import30.Config),this.parentInjector.get(import41.Form),this._Item_13_4,this.parentInjector.get(import34.App),this.parentInjector.get(import43.Platform),new import31.ElementRef(this._el_18),this.renderer,this._Content_9_4,this.parentInjector.get(import10.NavController,(null as any)),this._NgControl_18_7);
    this._appEl_18.initComponent(this._TextInput_18_9,[],compView_18);
    compView_18.create(this._TextInput_18_9,[],(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_13_0.reset([this._Label_15_3]);
    this._Item_13_4.contentLabel = this._query_Label_13_0.first;
    compView_13.create(this._Item_13_4,[
      [],
      [].concat([this._el_15]),
      [].concat([
        this._text_14,
        this._text_17,
        this._text_19
      ]
      ),
      [].concat([this._el_18]),
      []
    ]
    ,(null as any));
    this._text_20 = this.renderer.createText(this._el_11,'\n\n\n    ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','itemCadastrarEvento item item-block');
    this._appEl_21 = new import2.AppElement(21,11,this,this._el_21);
    var compView_21:any = import40.viewFactory_Item0(this.viewUtils,this.injector(21),this._appEl_21);
    this._Item_21_4 = new import22.Item(this.parentInjector.get(import41.Form),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_21),this.renderer);
    this._ItemContent_21_5 = new import22.ItemContent();
    this._query_Label_21_0 = new import23.QueryList<any>();
    this._query_Button_21_1 = new import23.QueryList<any>();
    this._query_Icon_21_2 = new import23.QueryList<any>();
    this._appEl_21.initComponent(this._Item_21_4,[],compView_21);
    this._text_22 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','labelCadastrarEvento');
    this.renderer.setElementAttribute(this._el_23,'stacked','');
    this._Label_23_3 = new import24.Label(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_23),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Descrição',(null as any));
    this._text_25 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'ion-textarea',(null as any));
    this.renderer.setElementAttribute(this._el_26,'name','descricao');
    this.renderer.setElementAttribute(this._el_26,'ngModel','');
    this.renderer.setElementAttribute(this._el_26,'required','');
    this.renderer.setElementAttribute(this._el_26,'rows','3');
    this.renderer.setElementAttribute(this._el_26,'type','text');
    this._appEl_26 = new import2.AppElement(26,21,this,this._el_26);
    var compView_26:any = import42.viewFactory_TextArea0(this.viewUtils,this.injector(26),this._appEl_26);
    this._RequiredValidator_26_4 = new import25.RequiredValidator();
    this._NG_VALIDATORS_26_5 = [this._RequiredValidator_26_4];
    this._NgModel_26_6 = new import26.NgModel(this._ControlContainer_11_4,this._NG_VALIDATORS_26_5,(null as any),(null as any));
    this._NgControl_26_7 = this._NgModel_26_6;
    this._NgControlStatus_26_8 = new import21.NgControlStatus(this._NgControl_26_7);
    this._TextArea_26_9 = new import27.TextArea(this.parentInjector.get(import30.Config),this.parentInjector.get(import41.Form),this._Item_21_4,this.parentInjector.get(import34.App),this.parentInjector.get(import43.Platform),new import31.ElementRef(this._el_26),this.renderer,this._Content_9_4,this.parentInjector.get(import10.NavController,(null as any)),this._NgControl_26_7);
    this._appEl_26.initComponent(this._TextArea_26_9,[],compView_26);
    compView_26.create(this._TextArea_26_9,[],(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_21_0.reset([this._Label_23_3]);
    this._Item_21_4.contentLabel = this._query_Label_21_0.first;
    compView_21.create(this._Item_21_4,[
      [],
      [].concat([this._el_23]),
      [].concat([
        this._text_22,
        this._text_25,
        this._text_27
      ]
      ),
      [].concat([this._el_26]),
      []
    ]
    ,(null as any));
    this._text_28 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_29,'full','');
    this.renderer.setElementAttribute(this._el_29,'ion-button','');
    this.renderer.setElementAttribute(this._el_29,'style','color: #209760; margin-left: 5px; margin-right: 5px;');
    this._appEl_29 = new import2.AppElement(29,11,this,this._el_29);
    var compView_29:any = import44.viewFactory_Button0(this.viewUtils,this.injector(29),this._appEl_29);
    this._Button_29_4 = new import28.Button((null as any),'',this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_29),this.renderer);
    this._appEl_29.initComponent(this._Button_29_4,[],compView_29);
    this._text_30 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_31,'name','checkmark-circle');
    this.renderer.setElementAttribute(this._el_31,'role','img');
    this._Icon_31_3 = new import29.Icon(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_31),this.renderer);
    this._text_32 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_29.create(this._Button_29_4,[[].concat([
        this._text_30,
        this._el_31,
        this._text_32
      ]
    )],(null as any));
    this._text_33 = this.renderer.createText(this._el_11,'\n\n\n  ',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_9.create(this._Content_9_4,[
      [],
      [].concat([
        this._text_10,
        this._el_11,
        this._text_34
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_35 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_11,'submit',this.eventHandler(this._handle_submit_11_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_11,'reset',this.eventHandler(this._handle_reset_11_1.bind(this)));
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    this._expr_9 = import8.UNINITIALIZED;
    this._expr_10 = import8.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_18,'ngModelChange',this.eventHandler(this._handle_ngModelChange_18_0.bind(this)));
    this._expr_12 = import8.UNINITIALIZED;
    this._expr_13 = import8.UNINITIALIZED;
    this._expr_14 = import8.UNINITIALIZED;
    this._expr_15 = import8.UNINITIALIZED;
    const subscription_0:any = this._NgModel_18_6.update.subscribe(this.eventHandler(this._handle_ngModelChange_18_0.bind(this)));
    this._expr_16 = import8.UNINITIALIZED;
    this._expr_17 = import8.UNINITIALIZED;
    this._expr_18 = import8.UNINITIALIZED;
    this._expr_19 = import8.UNINITIALIZED;
    this._expr_20 = import8.UNINITIALIZED;
    this._expr_21 = import8.UNINITIALIZED;
    this._expr_22 = import8.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_26,'ngModelChange',this.eventHandler(this._handle_ngModelChange_26_0.bind(this)));
    this._expr_24 = import8.UNINITIALIZED;
    this._expr_25 = import8.UNINITIALIZED;
    this._expr_26 = import8.UNINITIALIZED;
    this._expr_27 = import8.UNINITIALIZED;
    const subscription_1:any = this._NgModel_26_6.update.subscribe(this.eventHandler(this._handle_ngModelChange_26_0.bind(this)));
    this._expr_28 = import8.UNINITIALIZED;
    this._expr_29 = import8.UNINITIALIZED;
    this._expr_30 = import8.UNINITIALIZED;
    this._expr_31 = import8.UNINITIALIZED;
    this._expr_32 = import8.UNINITIALIZED;
    this._expr_33 = import8.UNINITIALIZED;
    this._expr_34 = import8.UNINITIALIZED;
    this._expr_36 = import8.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_29,'click',this.eventHandler(this._handle_click_29_0.bind(this)));
    this._expr_37 = import8.UNINITIALIZED;
    this._expr_38 = import8.UNINITIALIZED;
    this._expr_39 = import8.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import17.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import16.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import24.Label) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Label_15_3; }
    if (((token === import25.RequiredValidator) && (18 === requestNodeIndex))) { return this._RequiredValidator_18_4; }
    if (((token === import45.NG_VALIDATORS) && (18 === requestNodeIndex))) { return this._NG_VALIDATORS_18_5; }
    if (((token === import26.NgModel) && (18 === requestNodeIndex))) { return this._NgModel_18_6; }
    if (((token === import46.NgControl) && (18 === requestNodeIndex))) { return this._NgControl_18_7; }
    if (((token === import21.NgControlStatus) && (18 === requestNodeIndex))) { return this._NgControlStatus_18_8; }
    if (((token === import27.TextInput) && (18 === requestNodeIndex))) { return this._TextInput_18_9; }
    if (((token === import22.Item) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Item_13_4; }
    if (((token === import22.ItemContent) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ItemContent_13_5; }
    if (((token === import24.Label) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Label_23_3; }
    if (((token === import25.RequiredValidator) && (26 === requestNodeIndex))) { return this._RequiredValidator_26_4; }
    if (((token === import45.NG_VALIDATORS) && (26 === requestNodeIndex))) { return this._NG_VALIDATORS_26_5; }
    if (((token === import26.NgModel) && (26 === requestNodeIndex))) { return this._NgModel_26_6; }
    if (((token === import46.NgControl) && (26 === requestNodeIndex))) { return this._NgControl_26_7; }
    if (((token === import21.NgControlStatus) && (26 === requestNodeIndex))) { return this._NgControlStatus_26_8; }
    if (((token === import27.TextArea) && (26 === requestNodeIndex))) { return this._TextArea_26_9; }
    if (((token === import22.Item) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Item_21_4; }
    if (((token === import22.ItemContent) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._ItemContent_21_5; }
    if (((token === import29.Icon) && (31 === requestNodeIndex))) { return this._Icon_31_3; }
    if (((token === import28.Button) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Button_29_4; }
    if (((token === import20.NgForm) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._NgForm_11_3; }
    if (((token === import47.ControlContainer) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._ControlContainer_11_4; }
    if (((token === import21.NgControlStatusGroup) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._NgControlStatusGroup_11_5; }
    if (((token === import19.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    const currVal_12:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._RequiredValidator_18_4.required = currVal_12;
      this._expr_12 = currVal_12;
    }
    changes = (null as any);
    const currVal_14:any = 'nome';
    if (import5.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgModel_18_6.name = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import8.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this.context.grupoCad.nome;
    if (import5.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._NgModel_18_6.model = currVal_15;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import8.SimpleChange(this._expr_15,currVal_15);
      this._expr_15 = currVal_15;
    }
    if ((changes !== (null as any))) { this._NgModel_18_6.ngOnChanges(changes); }
    const currVal_22:any = 'text';
    if (import5.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._TextInput_18_9.type = currVal_22;
      this._expr_22 = currVal_22;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_18_9.ngOnInit(); }
    const currVal_24:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._RequiredValidator_26_4.required = currVal_24;
      this._expr_24 = currVal_24;
    }
    changes = (null as any);
    const currVal_26:any = 'descricao';
    if (import5.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._NgModel_26_6.name = currVal_26;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import8.SimpleChange(this._expr_26,currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this.context.grupoCad.descricao;
    if (import5.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._NgModel_26_6.model = currVal_27;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import8.SimpleChange(this._expr_27,currVal_27);
      this._expr_27 = currVal_27;
    }
    if ((changes !== (null as any))) { this._NgModel_26_6.ngOnChanges(changes); }
    const currVal_34:any = 'text';
    if (import5.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this._TextArea_26_9.type = currVal_34;
      this._expr_34 = currVal_34;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextArea_26_9.ngOnInit(); }
    changed = false;
    const currVal_37:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this._Button_29_4.full = currVal_37;
      changed = true;
      this._expr_37 = currVal_37;
    }
    if (changed) { this._appEl_29.componentView.markAsCheckOnce(); }
    const currVal_38:any = 'checkmark-circle';
    if (import5.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this._Icon_31_3.name = currVal_38;
      this._expr_38 = currVal_38;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_13_1.dirty) {
        this._query_Button_13_1.reset([]);
        this._Item_13_4._buttons = this._query_Button_13_1;
        this._query_Button_13_1.notifyOnChanges();
      }
      if (this._query_Icon_13_2.dirty) {
        this._query_Icon_13_2.reset([]);
        this._Item_13_4._icons = this._query_Icon_13_2;
        this._query_Icon_13_2.notifyOnChanges();
      }
      if (this._query_Button_21_1.dirty) {
        this._query_Button_21_1.reset([]);
        this._Item_21_4._buttons = this._query_Button_21_1;
        this._query_Button_21_1.notifyOnChanges();
      }
      if (this._query_Icon_21_2.dirty) {
        this._query_Icon_21_2.reset([]);
        this._Item_21_4._icons = this._query_Icon_21_2;
        this._query_Icon_21_2.notifyOnChanges();
      }
      this._TextInput_18_9.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_13_4.ngAfterContentInit(); }
      this._TextArea_26_9.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_21_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_29_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._NgControlStatusGroup_11_5.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_11,'ng-untouched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_11_5.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_11,'ng-touched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_11_5.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_11,'ng-pristine',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_11_5.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_11,'ng-dirty',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_11_5.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_11,'ng-valid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_11_5.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_11,'ng-invalid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_13:any = (this._RequiredValidator_18_4.required? '': (null as any));
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementAttribute(this._el_18,'required',((currVal_13 == (null as any))? (null as any): currVal_13.toString()));
      this._expr_13 = currVal_13;
    }
    const currVal_16:any = this._NgControlStatus_18_8.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_18,'ng-untouched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_18_8.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_18,'ng-touched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_18_8.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_18,'ng-pristine',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_18_8.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_18,'ng-dirty',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_18_8.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_18,'ng-valid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_18_8.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_18,'ng-invalid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_25:any = (this._RequiredValidator_26_4.required? '': (null as any));
    if (import5.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementAttribute(this._el_26,'required',((currVal_25 == (null as any))? (null as any): currVal_25.toString()));
      this._expr_25 = currVal_25;
    }
    const currVal_28:any = this._NgControlStatus_26_8.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_26,'ng-untouched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_26_8.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_26,'ng-touched',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_26_8.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_26,'ng-pristine',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_26_8.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_26,'ng-dirty',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_26_8.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_26,'ng-valid',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_26_8.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_26,'ng-invalid',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_36:boolean = !this._NgForm_11_3.valid;
    if (import5.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementProperty(this._el_29,'disabled',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_39:any = this._Icon_31_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_31,'hide',currVal_39);
      this._expr_39 = currVal_39;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._NgModel_18_6.ngOnDestroy();
    this._TextInput_18_9.ngOnDestroy();
    this._NgModel_26_6.ngOnDestroy();
    this._TextArea_26_9.ngOnDestroy();
    this._Icon_31_3.ngOnDestroy();
    this._Content_9_4.ngOnDestroy();
  }
  private _handle_submit_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_11_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_11_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_11_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.grupoCad.nome = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.grupoCad.descricao = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.funcaoPraAceitarSubmeterForm(this._NgForm_11_3)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_CadastrarGrupoPage0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.CadastrarGrupoPage> {
  if ((renderType_CadastrarGrupoPage === (null as any))) { (renderType_CadastrarGrupoPage = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,styles_CadastrarGrupoPage,{})); }
  return new _View_CadastrarGrupoPage0(viewUtils,parentInjector,declarationEl);
}