/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../services/UsuarioService';
import * as import4 from './home';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/http/src/http';
import * as import10 from 'ionic-angular/navigation/nav-controller';
import * as import11 from 'ionic-angular/platform/platform';
import * as import12 from '../../services/user-data';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from 'ionic-angular/components/content/content';
import * as import16 from '@angular/forms/src/directives/ng_form';
import * as import17 from '@angular/forms/src/directives/ng_control_status';
import * as import18 from 'ionic-angular/components/list/list';
import * as import19 from 'ionic-angular/components/item/item';
import * as import20 from '@angular/core/src/linker/query_list';
import * as import21 from '@angular/forms/src/directives/validators';
import * as import22 from '@angular/forms/src/directives/ng_model';
import * as import23 from 'ionic-angular/components/input/input';
import * as import24 from 'ionic-angular/components/button/button';
import * as import25 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import26 from 'ionic-angular/config/config';
import * as import27 from '@angular/core/src/linker/element_ref';
import * as import28 from 'ionic-angular/components/app/app';
import * as import29 from 'ionic-angular/util/keyboard';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from 'ionic-angular/navigation/view-controller';
import * as import32 from 'ionic-angular/components/tabs/tabs';
import * as import33 from 'ionic-angular/gestures/gesture-controller';
import * as import34 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import35 from 'ionic-angular/util/form';
import * as import36 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import37 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import38 from '@angular/forms/src/validators';
import * as import39 from '@angular/forms/src/directives/ng_control';
import * as import40 from '@angular/forms/src/directives/control_container';
var renderType_HomePage_Host:import0.RenderComponentType = (null as any);
class _View_HomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UsuarioService_0_4:import3.UsuarioService;
  _HomePage_0_5:import4.HomePage;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage_Host0,renderType_HomePage_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UsuarioService_0_4 = new import3.UsuarioService(this.parentInjector.get(import9.Http));
    this._HomePage_0_5 = new import4.HomePage(this.parentInjector.get(import10.NavController),this._UsuarioService_0_4,this.parentInjector.get(import11.Platform),this.parentInjector.get(import12.UserData));
    this._appEl_0.initComponent(this._HomePage_0_5,[],compView_0);
    compView_0.create(this._HomePage_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.UsuarioService) && (0 === requestNodeIndex))) { return this._UsuarioService_0_4; }
    if (((token === import4.HomePage) && (0 === requestNodeIndex))) { return this._HomePage_0_5; }
    return notFoundResult;
  }
}
function viewFactory_HomePage_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HomePage_Host === (null as any))) { (renderType_HomePage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,[],{})); }
  return new _View_HomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomePageNgFactory:import14.ComponentFactory<import4.HomePage> = new import14.ComponentFactory<import4.HomePage>('ng-component',viewFactory_HomePage_Host0,import4.HomePage);
const styles_HomePage:any[] = [];
var renderType_HomePage:import0.RenderComponentType = (null as any);
class _View_HomePage0 extends import1.AppView<import4.HomePage> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Content_0_4:import15.Content;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _NgForm_7_3:import16.NgForm;
  _ControlContainer_7_4:any;
  _NgControlStatusGroup_7_5:import17.NgControlStatusGroup;
  _text_8:any;
  _el_9:any;
  _List_9_3:import18.List;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _Item_11_4:import19.Item;
  _ItemContent_11_5:import19.ItemContent;
  _query_Label_11_0:import20.QueryList<any>;
  _query_Button_11_1:import20.QueryList<any>;
  _query_Icon_11_2:import20.QueryList<any>;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _RequiredValidator_13_4:import21.RequiredValidator;
  _NG_VALIDATORS_13_5:any[];
  _NgModel_13_6:import22.NgModel;
  _NgControl_13_7:any;
  _NgControlStatus_13_8:import17.NgControlStatus;
  _TextInput_13_9:import23.TextInput;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _Item_19_4:import19.Item;
  _ItemContent_19_5:import19.ItemContent;
  _query_Label_19_0:import20.QueryList<any>;
  _query_Button_19_1:import20.QueryList<any>;
  _query_Icon_19_2:import20.QueryList<any>;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _RequiredValidator_21_4:import21.RequiredValidator;
  _NG_VALIDATORS_21_5:any[];
  _NgModel_21_6:import22.NgModel;
  _NgControl_21_7:any;
  _NgControlStatus_21_8:import17.NgControlStatus;
  _TextInput_21_9:import23.TextInput;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _Button_30_4:import24.Button;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_38:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage0,renderType_HomePage,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','bg');
    this.renderer.setElementAttribute(this._el_0,'scroll','false');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import25.viewFactory_Content0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Content_0_4 = new import15.Content(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import28.App),this.parentInjector.get(import29.Keyboard),this.parentInjector.get(import30.NgZone),this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import32.Tabs,(null as any)));
    this._appEl_0.initComponent(this._Content_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'style','margin-top: 30px;');
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'img',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','inicialLogo');
    this.renderer.setElementAttribute(this._el_4,'src','assets/img/logo-branca.png');
    this.renderer.setElementAttribute(this._el_4,'width','70%');
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'form',(null as any));
    this.renderer.setElementAttribute(this._el_7,'novalidate','');
    this._NgForm_7_3 = new import16.NgForm((null as any),(null as any));
    this._ControlContainer_7_4 = this._NgForm_7_3;
    this._NgControlStatusGroup_7_5 = new import17.NgControlStatusGroup(this._ControlContainer_7_4);
    this._text_8 = this.renderer.createText(this._el_7,'\n          ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','login');
    this._List_9_3 = new import18.List(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import33.GestureController));
    this._text_10 = this.renderer.createText(this._el_9,'\n              ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','item item-block');
    this._appEl_11 = new import2.AppElement(11,9,this,this._el_11);
    var compView_11:any = import34.viewFactory_Item0(this.viewUtils,this.injector(11),this._appEl_11);
    this._Item_11_4 = new import19.Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_11),this.renderer);
    this._ItemContent_11_5 = new import19.ItemContent();
    this._query_Label_11_0 = new import20.QueryList<any>();
    this._query_Button_11_1 = new import20.QueryList<any>();
    this._query_Icon_11_2 = new import20.QueryList<any>();
    this._appEl_11.initComponent(this._Item_11_4,[],compView_11);
    this._text_12 = this.renderer.createText((null as any),'\n                  ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_13,'name','username');
    this.renderer.setElementAttribute(this._el_13,'ngModel','');
    this.renderer.setElementAttribute(this._el_13,'placeholder','Username');
    this.renderer.setElementAttribute(this._el_13,'required','');
    this.renderer.setElementAttribute(this._el_13,'type','text');
    this._appEl_13 = new import2.AppElement(13,11,this,this._el_13);
    var compView_13:any = import36.viewFactory_TextInput0(this.viewUtils,this.injector(13),this._appEl_13);
    this._RequiredValidator_13_4 = new import21.RequiredValidator();
    this._NG_VALIDATORS_13_5 = [this._RequiredValidator_13_4];
    this._NgModel_13_6 = new import22.NgModel(this._ControlContainer_7_4,this._NG_VALIDATORS_13_5,(null as any),(null as any));
    this._NgControl_13_7 = this._NgModel_13_6;
    this._NgControlStatus_13_8 = new import17.NgControlStatus(this._NgControl_13_7);
    this._TextInput_13_9 = new import23.TextInput(this.parentInjector.get(import26.Config),this.parentInjector.get(import35.Form),this._Item_11_4,this.parentInjector.get(import28.App),this.parentInjector.get(import11.Platform),new import27.ElementRef(this._el_13),this.renderer,this._Content_0_4,this.parentInjector.get(import10.NavController,(null as any)),this._NgControl_13_7);
    this._appEl_13.initComponent(this._TextInput_13_9,[],compView_13);
    compView_13.create(this._TextInput_13_9,[],(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._query_Label_11_0.reset([]);
    this._Item_11_4.contentLabel = this._query_Label_11_0.first;
    compView_11.create(this._Item_11_4,[
      [],
      [],
      [].concat([
        this._text_12,
        this._text_14
      ]
      ),
      [].concat([this._el_13]),
      []
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText(this._el_9,'\n              ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_9,'p',(null as any));
    this.renderer.setElementAttribute(this._el_16,'danger','');
    this.renderer.setElementAttribute(this._el_16,'padding-left','');
    this._text_17 = this.renderer.createText(this._el_16,'\n                Username is required\n              ',(null as any));
    this._text_18 = this.renderer.createText(this._el_9,'\n\n              ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_9,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','item item-block');
    this._appEl_19 = new import2.AppElement(19,9,this,this._el_19);
    var compView_19:any = import34.viewFactory_Item0(this.viewUtils,this.injector(19),this._appEl_19);
    this._Item_19_4 = new import19.Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_19),this.renderer);
    this._ItemContent_19_5 = new import19.ItemContent();
    this._query_Label_19_0 = new import20.QueryList<any>();
    this._query_Button_19_1 = new import20.QueryList<any>();
    this._query_Icon_19_2 = new import20.QueryList<any>();
    this._appEl_19.initComponent(this._Item_19_4,[],compView_19);
    this._text_20 = this.renderer.createText((null as any),'\n                  ',(null as any));
    this._el_21 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_21,'name','password');
    this.renderer.setElementAttribute(this._el_21,'ngModel','');
    this.renderer.setElementAttribute(this._el_21,'placeholder','Password');
    this.renderer.setElementAttribute(this._el_21,'required','');
    this.renderer.setElementAttribute(this._el_21,'type','password');
    this._appEl_21 = new import2.AppElement(21,19,this,this._el_21);
    var compView_21:any = import36.viewFactory_TextInput0(this.viewUtils,this.injector(21),this._appEl_21);
    this._RequiredValidator_21_4 = new import21.RequiredValidator();
    this._NG_VALIDATORS_21_5 = [this._RequiredValidator_21_4];
    this._NgModel_21_6 = new import22.NgModel(this._ControlContainer_7_4,this._NG_VALIDATORS_21_5,(null as any),(null as any));
    this._NgControl_21_7 = this._NgModel_21_6;
    this._NgControlStatus_21_8 = new import17.NgControlStatus(this._NgControl_21_7);
    this._TextInput_21_9 = new import23.TextInput(this.parentInjector.get(import26.Config),this.parentInjector.get(import35.Form),this._Item_19_4,this.parentInjector.get(import28.App),this.parentInjector.get(import11.Platform),new import27.ElementRef(this._el_21),this.renderer,this._Content_0_4,this.parentInjector.get(import10.NavController,(null as any)),this._NgControl_21_7);
    this._appEl_21.initComponent(this._TextInput_21_9,[],compView_21);
    compView_21.create(this._TextInput_21_9,[],(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._query_Label_19_0.reset([]);
    this._Item_19_4.contentLabel = this._query_Label_19_0.first;
    compView_19.create(this._Item_19_4,[
      [],
      [],
      [].concat([
        this._text_20,
        this._text_22
      ]
      ),
      [].concat([this._el_21]),
      []
    ]
    ,(null as any));
    this._text_23 = this.renderer.createText(this._el_9,'\n              ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_9,'p',(null as any));
    this.renderer.setElementAttribute(this._el_24,'danger','');
    this.renderer.setElementAttribute(this._el_24,'padding-left','');
    this._text_25 = this.renderer.createText(this._el_24,'\n                Password is required\n              ',(null as any));
    this._text_26 = this.renderer.createText(this._el_9,'\n\n          ',(null as any));
    this._text_27 = this.renderer.createText(this._el_7,'\n\n          ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'padding','');
    this._text_29 = this.renderer.createText(this._el_28,'\n              ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'button',(null as any));
    this.renderer.setElementAttribute(this._el_30,'full','');
    this.renderer.setElementAttribute(this._el_30,'ion-button','');
    this._appEl_30 = new import2.AppElement(30,28,this,this._el_30);
    var compView_30:any = import37.viewFactory_Button0(this.viewUtils,this.injector(30),this._appEl_30);
    this._Button_30_4 = new import24.Button((null as any),'',this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_30),this.renderer);
    this._appEl_30.initComponent(this._Button_30_4,[],compView_30);
    this._text_31 = this.renderer.createText((null as any),'LOGIN',(null as any));
    compView_30.create(this._Button_30_4,[[].concat([this._text_31])],(null as any));
    this._text_32 = this.renderer.createText(this._el_28,'\n          ',(null as any));
    this._text_33 = this.renderer.createText(this._el_7,'\n\n          ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_34,'id','textoEsqueceuSenha');
    this.renderer.setElementAttribute(this._el_34,'padding','');
    this._text_35 = this.renderer.createText(this._el_34,'\n      		    ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_34,'a',(null as any));
    this.renderer.setElementAttribute(this._el_36,'href','#');
    this.renderer.setElementAttribute(this._el_36,'id','linkEsqueceuSenha');
    this._text_37 = this.renderer.createText(this._el_36,'Esqueceu sua senha?',(null as any));
    this._text_38 = this.renderer.createText(this._el_34,'\n          ',(null as any));
    this._text_39 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n\n\n\n    ',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'hr',(null as any));
    this.renderer.setElementAttribute(this._el_41,'id','linhaSeparadora');
    this._text_42 = this.renderer.createText((null as any),'\n\n\n    ',(null as any));
    this._el_43 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_43,'id','textoCriarConta');
    this._text_44 = this.renderer.createText(this._el_43,'\n      ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_43,'p',(null as any));
    this.renderer.setElementAttribute(this._el_45,'id','textoNaoTemConta');
    this._text_46 = this.renderer.createText(this._el_45,'Não tem uma conta?',(null as any));
    this._text_47 = this.renderer.createText(this._el_43,'\n      ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_43,'a',(null as any));
    this.renderer.setElementAttribute(this._el_48,'href','#');
    this.renderer.setElementAttribute(this._el_48,'id','textoCriarConta');
    this._text_49 = this.renderer.createText(this._el_48,'Criar uma conta',(null as any));
    this._el_50 = this.renderer.createElement(this._el_43,'br',(null as any));
    this._text_51 = this.renderer.createText(this._el_43,'\n    ',(null as any));
    this._text_52 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_0.create(this._Content_0_4,[
      [],
      [].concat([
        this._text_1,
        this._el_2,
        this._text_6,
        this._el_7,
        this._text_40,
        this._el_41,
        this._text_42,
        this._el_43,
        this._text_52
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_53 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_7,'submit',this.eventHandler(this._handle_submit_7_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_7,'reset',this.eventHandler(this._handle_reset_7_1.bind(this)));
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_13,'ngModelChange',this.eventHandler(this._handle_ngModelChange_13_0.bind(this)));
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    this._expr_12 = import8.UNINITIALIZED;
    this._expr_13 = import8.UNINITIALIZED;
    const subscription_0:any = this._NgModel_13_6.update.subscribe(this.eventHandler(this._handle_ngModelChange_13_0.bind(this)));
    this._expr_14 = import8.UNINITIALIZED;
    this._expr_15 = import8.UNINITIALIZED;
    this._expr_16 = import8.UNINITIALIZED;
    this._expr_17 = import8.UNINITIALIZED;
    this._expr_18 = import8.UNINITIALIZED;
    this._expr_19 = import8.UNINITIALIZED;
    this._expr_20 = import8.UNINITIALIZED;
    this._expr_21 = import8.UNINITIALIZED;
    this._expr_22 = import8.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_21,'ngModelChange',this.eventHandler(this._handle_ngModelChange_21_0.bind(this)));
    this._expr_24 = import8.UNINITIALIZED;
    this._expr_25 = import8.UNINITIALIZED;
    this._expr_26 = import8.UNINITIALIZED;
    this._expr_27 = import8.UNINITIALIZED;
    const subscription_1:any = this._NgModel_21_6.update.subscribe(this.eventHandler(this._handle_ngModelChange_21_0.bind(this)));
    this._expr_28 = import8.UNINITIALIZED;
    this._expr_29 = import8.UNINITIALIZED;
    this._expr_30 = import8.UNINITIALIZED;
    this._expr_31 = import8.UNINITIALIZED;
    this._expr_32 = import8.UNINITIALIZED;
    this._expr_33 = import8.UNINITIALIZED;
    this._expr_34 = import8.UNINITIALIZED;
    this._expr_35 = import8.UNINITIALIZED;
    this._expr_36 = import8.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_30,'click',this.eventHandler(this._handle_click_30_0.bind(this)));
    this._expr_38 = import8.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_36,'click',this.eventHandler(this._handle_click_36_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_48,'click',this.eventHandler(this._handle_click_48_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.RequiredValidator) && (13 === requestNodeIndex))) { return this._RequiredValidator_13_4; }
    if (((token === import38.NG_VALIDATORS) && (13 === requestNodeIndex))) { return this._NG_VALIDATORS_13_5; }
    if (((token === import22.NgModel) && (13 === requestNodeIndex))) { return this._NgModel_13_6; }
    if (((token === import39.NgControl) && (13 === requestNodeIndex))) { return this._NgControl_13_7; }
    if (((token === import17.NgControlStatus) && (13 === requestNodeIndex))) { return this._NgControlStatus_13_8; }
    if (((token === import23.TextInput) && (13 === requestNodeIndex))) { return this._TextInput_13_9; }
    if (((token === import19.Item) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Item_11_4; }
    if (((token === import19.ItemContent) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ItemContent_11_5; }
    if (((token === import21.RequiredValidator) && (21 === requestNodeIndex))) { return this._RequiredValidator_21_4; }
    if (((token === import38.NG_VALIDATORS) && (21 === requestNodeIndex))) { return this._NG_VALIDATORS_21_5; }
    if (((token === import22.NgModel) && (21 === requestNodeIndex))) { return this._NgModel_21_6; }
    if (((token === import39.NgControl) && (21 === requestNodeIndex))) { return this._NgControl_21_7; }
    if (((token === import17.NgControlStatus) && (21 === requestNodeIndex))) { return this._NgControlStatus_21_8; }
    if (((token === import23.TextInput) && (21 === requestNodeIndex))) { return this._TextInput_21_9; }
    if (((token === import19.Item) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Item_19_4; }
    if (((token === import19.ItemContent) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._ItemContent_19_5; }
    if (((token === import18.List) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._List_9_3; }
    if (((token === import24.Button) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Button_30_4; }
    if (((token === import16.NgForm) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._NgForm_7_3; }
    if (((token === import40.ControlContainer) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._ControlContainer_7_4; }
    if (((token === import17.NgControlStatusGroup) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._NgControlStatusGroup_7_5; }
    if (((token === import15.Content) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Content_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_0_4.ngOnInit(); }
    const currVal_10:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._RequiredValidator_13_4.required = currVal_10;
      this._expr_10 = currVal_10;
    }
    changes = (null as any);
    const currVal_12:any = 'username';
    if (import5.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgModel_13_6.name = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import8.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this.context.login.username;
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgModel_13_6.model = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import8.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._NgModel_13_6.ngOnChanges(changes); }
    const currVal_20:any = 'Username';
    if (import5.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._TextInput_13_9.placeholder = currVal_20;
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = 'text';
    if (import5.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._TextInput_13_9.type = currVal_21;
      this._expr_21 = currVal_21;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_13_9.ngOnInit(); }
    const currVal_24:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._RequiredValidator_21_4.required = currVal_24;
      this._expr_24 = currVal_24;
    }
    changes = (null as any);
    const currVal_26:any = 'password';
    if (import5.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._NgModel_21_6.name = currVal_26;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import8.SimpleChange(this._expr_26,currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this.context.login.password;
    if (import5.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._NgModel_21_6.model = currVal_27;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import8.SimpleChange(this._expr_27,currVal_27);
      this._expr_27 = currVal_27;
    }
    if ((changes !== (null as any))) { this._NgModel_21_6.ngOnChanges(changes); }
    const currVal_34:any = 'Password';
    if (import5.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this._TextInput_21_9.placeholder = currVal_34;
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = 'password';
    if (import5.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this._TextInput_21_9.type = currVal_35;
      this._expr_35 = currVal_35;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_21_9.ngOnInit(); }
    changed = false;
    const currVal_38:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this._Button_30_4.full = currVal_38;
      changed = true;
      this._expr_38 = currVal_38;
    }
    if (changed) { this._appEl_30.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_11_1.dirty) {
        this._query_Button_11_1.reset([]);
        this._Item_11_4._buttons = this._query_Button_11_1;
        this._query_Button_11_1.notifyOnChanges();
      }
      if (this._query_Icon_11_2.dirty) {
        this._query_Icon_11_2.reset([]);
        this._Item_11_4._icons = this._query_Icon_11_2;
        this._query_Icon_11_2.notifyOnChanges();
      }
      if (this._query_Button_19_1.dirty) {
        this._query_Button_19_1.reset([]);
        this._Item_19_4._buttons = this._query_Button_19_1;
        this._query_Button_19_1.notifyOnChanges();
      }
      if (this._query_Icon_19_2.dirty) {
        this._query_Icon_19_2.reset([]);
        this._Item_19_4._icons = this._query_Icon_19_2;
        this._query_Icon_19_2.notifyOnChanges();
      }
      this._TextInput_13_9.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_11_4.ngAfterContentInit(); }
      this._TextInput_21_9.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_19_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_30_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Content_0_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_3:any = this._NgControlStatusGroup_7_5.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_7,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_7_5.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_7,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_7_5.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_7,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_7_5.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_7,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_7_5.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_7,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_7_5.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_7,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = (this._RequiredValidator_13_4.required? '': (null as any));
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementAttribute(this._el_13,'required',((currVal_11 == (null as any))? (null as any): currVal_11.toString()));
      this._expr_11 = currVal_11;
    }
    const currVal_14:any = this._NgControlStatus_13_8.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_13,'ng-untouched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_13_8.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_13,'ng-touched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_13_8.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_13,'ng-pristine',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_13_8.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_13,'ng-dirty',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_13_8.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_13,'ng-valid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_13_8.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_13,'ng-invalid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_22:any = (this._NgModel_13_6.valid || (this.context.submitted == false));
    if (import5.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementProperty(this._el_16,'hidden',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_25:any = (this._RequiredValidator_21_4.required? '': (null as any));
    if (import5.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementAttribute(this._el_21,'required',((currVal_25 == (null as any))? (null as any): currVal_25.toString()));
      this._expr_25 = currVal_25;
    }
    const currVal_28:any = this._NgControlStatus_21_8.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_21,'ng-untouched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_21_8.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_21,'ng-touched',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_21_8.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_21,'ng-pristine',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_21_8.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_21,'ng-dirty',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_21_8.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_21,'ng-valid',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_21_8.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_21,'ng-invalid',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_36:any = (this._NgModel_21_6.valid || (this.context.submitted == false));
    if (import5.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementProperty(this._el_24,'hidden',currVal_36);
      this._expr_36 = currVal_36;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_13_6.ngOnDestroy();
    this._TextInput_13_9.ngOnDestroy();
    this._NgModel_21_6.ngOnDestroy();
    this._TextInput_21_9.ngOnDestroy();
    this._Content_0_4.ngOnDestroy();
  }
  private _handle_submit_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_7_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_7_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_7_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.login.username = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.login.password = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit(this._NgForm_7_3)) !== false);
    return (true && pd_0);
  }
  private _handle_click_36_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.forgotPwd()) !== false);
    return (true && pd_0);
  }
  private _handle_click_48_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doSignup()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HomePage0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.HomePage> {
  if ((renderType_HomePage === (null as any))) { (renderType_HomePage = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_HomePage,{})); }
  return new _View_HomePage0(viewUtils,parentInjector,declarationEl);
}