/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../services/NotificaoService';
import * as import4 from './notificacoes';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/http/src/http';
import * as import10 from 'ionic-angular/navigation/nav-controller';
import * as import11 from 'ionic-angular/navigation/nav-params';
import * as import12 from '../../services/user-data';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from 'ionic-angular/components/toolbar/toolbar';
import * as import16 from 'ionic-angular/components/navbar/navbar';
import * as import17 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import18 from 'ionic-angular/components/content/content';
import * as import19 from 'ionic-angular/components/refresher/refresher';
import * as import20 from 'ionic-angular/components/refresher/refresher-content';
import * as import21 from '@angular/common/src/directives/ng_for';
import * as import22 from 'ionic-angular/config/config';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from 'ionic-angular/navigation/view-controller';
import * as import25 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import26 from 'ionic-angular/components/app/app';
import * as import27 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import28 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import29 from 'ionic-angular/util/keyboard';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from 'ionic-angular/components/tabs/tabs';
import * as import32 from 'ionic-angular/gestures/gesture-controller';
import * as import33 from '../../node_modules/ionic-angular/components/refresher/refresher-content.ngfactory';
import * as import34 from '@angular/core/src/linker/template_ref';
import * as import35 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import36 from '@angular/core/src/security';
import * as import37 from '@angular/common/src/directives/ng_if';
import * as import38 from 'ionic-angular/components/card/card';
import * as import39 from 'ionic-angular/components/item/item';
import * as import40 from '@angular/core/src/linker/query_list';
import * as import41 from 'ionic-angular/components/avatar/avatar';
import * as import42 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import43 from 'ionic-angular/util/form';
var renderType_NotificacoesPage_Host:import0.RenderComponentType = (null as any);
class _View_NotificacoesPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _NotificaoService_0_4:import3.NotificaoService;
  _NotificacoesPage_0_5:import4.NotificacoesPage;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_NotificacoesPage_Host0,renderType_NotificacoesPage_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_NotificacoesPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._NotificaoService_0_4 = new import3.NotificaoService(this.parentInjector.get(import9.Http));
    this._NotificacoesPage_0_5 = new import4.NotificacoesPage(this.parentInjector.get(import10.NavController),this._NotificaoService_0_4,this.parentInjector.get(import11.NavParams),this.parentInjector.get(import12.UserData));
    this._appEl_0.initComponent(this._NotificacoesPage_0_5,[],compView_0);
    compView_0.create(this._NotificacoesPage_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.NotificaoService) && (0 === requestNodeIndex))) { return this._NotificaoService_0_4; }
    if (((token === import4.NotificacoesPage) && (0 === requestNodeIndex))) { return this._NotificacoesPage_0_5; }
    return notFoundResult;
  }
}
function viewFactory_NotificacoesPage_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_NotificacoesPage_Host === (null as any))) { (renderType_NotificacoesPage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,[],{})); }
  return new _View_NotificacoesPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const NotificacoesPageNgFactory:import14.ComponentFactory<import4.NotificacoesPage> = new import14.ComponentFactory<import4.NotificacoesPage>('ng-component',viewFactory_NotificacoesPage_Host0,import4.NotificacoesPage);
const styles_NotificacoesPage:any[] = [];
var renderType_NotificacoesPage:import0.RenderComponentType = (null as any);
class _View_NotificacoesPage0 extends import1.AppView<import4.NotificacoesPage> {
  _el_0:any;
  _Header_0_3:import15.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import16.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import17.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import18.Content;
  _text_10:any;
  _el_11:any;
  _Refresher_11_3:import19.Refresher;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _RefresherContent_13_4:import20.RefresherContent;
  _text_14:any;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _TemplateRef_16_5:any;
  _NgFor_16_6:import21.NgFor;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_NotificacoesPage0,renderType_NotificacoesPage,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import15.Header(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import24.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import25.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import16.Navbar(this.parentInjector.get(import26.App),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import10.NavController,(null as any)),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import27.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import17.ToolbarTitle(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import15.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'Notificações',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','notificacoes bg-branco');
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import28.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import18.Content(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import26.App),this.parentInjector.get(import29.Keyboard),this.parentInjector.get(import30.NgZone),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import31.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-refresher',(null as any));
    this._Refresher_11_3 = new import19.Refresher(this._Content_9_4,this.parentInjector.get(import30.NgZone),this.parentInjector.get(import32.GestureController));
    this._text_12 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-refresher-content',(null as any));
    this._appEl_13 = new import2.AppElement(13,11,this,this._el_13);
    var compView_13:any = import33.viewFactory_RefresherContent0(this.viewUtils,this.injector(13),this._appEl_13);
    this._RefresherContent_13_4 = new import20.RefresherContent(this._Refresher_11_3,this.parentInjector.get(import22.Config));
    this._appEl_13.initComponent(this._RefresherContent_13_4,[],compView_13);
    compView_13.create(this._RefresherContent_13_4,[],(null as any));
    this._text_14 = this.renderer.createText(this._el_11,'\n  ',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_16 = new import2.AppElement(16,9,this,this._anchor_16);
    this._TemplateRef_16_5 = new import34.TemplateRef_(this._appEl_16,viewFactory_NotificacoesPage1);
    this._NgFor_16_6 = new import21.NgFor(this._appEl_16.vcRef,this._TemplateRef_16_5,this.parentInjector.get(import35.IterableDiffers),this.ref);
    this._text_17 = this.renderer.createText((null as any),'\n\n\n\n',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_9.create(this._Content_9_4,[
      [],
      [].concat([
        this._text_10,
        this._text_15,
        this._appEl_16,
        this._text_17,
        this._text_18
      ]
      ),
      [].concat([this._el_11])
    ]
    ,(null as any));
    this._text_19 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_11,'ionRefresh',this.eventHandler(this._handle_ionRefresh_11_0.bind(this)));
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    const subscription_0:any = this._Refresher_11_3.ionRefresh.subscribe(this.eventHandler(this._handle_ionRefresh_11_0.bind(this)));
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._text_18,
      this._text_19
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import16.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import15.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import20.RefresherContent) && (13 === requestNodeIndex))) { return this._RefresherContent_13_4; }
    if (((token === import19.Refresher) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Refresher_11_3; }
    if (((token === import34.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import21.NgFor) && (16 === requestNodeIndex))) { return this._NgFor_16_6; }
    if (((token === import18.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Refresher_11_3.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RefresherContent_13_4.ngOnInit(); }
    changes = (null as any);
    const currVal_7:any = this.context.notificacoes;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgFor_16_6.ngForOf = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== (null as any))) { this._NgFor_16_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_16_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = (this._Refresher_11_3.state !== 'inactive');
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_11,'refresher-active',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._Refresher_11_3._top;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementStyle(this._el_11,'top',((this.viewUtils.sanitizer.sanitize(import36.SecurityContext.STYLE,currVal_5) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import36.SecurityContext.STYLE,currVal_5).toString()));
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._RefresherContent_13_4.r.state;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementAttribute(this._el_13,'state',((currVal_6 == (null as any))? (null as any): currVal_6.toString()));
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Refresher_11_3.ngOnDestroy();
    this._Content_9_4.ngOnDestroy();
  }
  private _handle_ionRefresh_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doRefresh($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_NotificacoesPage0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.NotificacoesPage> {
  if ((renderType_NotificacoesPage === (null as any))) { (renderType_NotificacoesPage = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_NotificacoesPage,{})); }
  return new _View_NotificacoesPage0(viewUtils,parentInjector,declarationEl);
}
class _View_NotificacoesPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import37.NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import37.NgIf;
  _text_5:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_NotificacoesPage1,renderType_NotificacoesPage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n\n    ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import34.TemplateRef_(this._appEl_2,viewFactory_NotificacoesPage2);
    this._NgIf_2_6 = new import37.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n\n\n    ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_4 = new import2.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import34.TemplateRef_(this._appEl_4,viewFactory_NotificacoesPage5);
    this._NgIf_4_6 = new import37.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_0,'\n\n\n  ',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import37.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import34.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import37.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = (this.context.$implicit.tipo == 1);
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = (this.context.$implicit.tipo == 4);
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_4_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NotificacoesPage1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NotificacoesPage1(viewUtils,parentInjector,declarationEl);
}
class _View_NotificacoesPage2 extends import1.AppView<any> {
  _el_0:any;
  _Card_0_3:import38.Card;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Item_2_4:import39.Item;
  _ItemContent_2_5:import39.ItemContent;
  _query_Label_2_0:import40.QueryList<any>;
  _query_Button_2_1:import40.QueryList<any>;
  _query_Icon_2_2:import40.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _Avatar_4_3:import41.Avatar;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import37.NgIf;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _TemplateRef_8_5:any;
  _NgIf_8_6:import37.NgIf;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_NotificacoesPage2,renderType_NotificacoesPage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','cardFeed');
    this._Card_0_3 = new import38.Card(this.parent.parent.parentInjector.get(import22.Config),new import23.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  	  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import42.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import39.Item(this.parent.parent.parentInjector.get(import43.Form),this.parent.parent.parentInjector.get(import22.Config),new import23.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import39.ItemContent();
    this._query_Label_2_0 = new import40.QueryList<any>();
    this._query_Button_2_1 = new import40.QueryList<any>();
    this._query_Icon_2_2 = new import40.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_4,'item-left','');
    this._Avatar_4_3 = new import41.Avatar();
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._appEl_6 = new import2.AppElement(6,4,this,this._anchor_6);
    this._TemplateRef_6_5 = new import34.TemplateRef_(this._appEl_6,viewFactory_NotificacoesPage3);
    this._NgIf_6_6 = new import37.NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._appEl_8 = new import2.AppElement(8,4,this,this._anchor_8);
    this._TemplateRef_8_5 = new import34.TemplateRef_(this._appEl_8,viewFactory_NotificacoesPage4);
    this._NgIf_8_6 = new import37.NgIf(this._appEl_8.vcRef,this._TemplateRef_8_5);
    this._text_9 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n  	      ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'h4',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n  	      ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n  	  ',(null as any));
    this._query_Label_2_0.reset([]);
    this._Item_2_4.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4,[
      [].concat([this._el_4]),
      [],
      [].concat([
        this._text_3,
        this._text_10,
        this._el_11,
        this._text_13,
        this._el_14,
        this._text_16,
        this._text_17
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n\n  	',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import37.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6; }
    if (((token === import34.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import37.NgIf) && (8 === requestNodeIndex))) { return this._NgIf_8_6; }
    if (((token === import41.Avatar) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Avatar_4_3; }
    if (((token === import39.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Item_2_4; }
    if (((token === import39.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._ItemContent_2_5; }
    if (((token === import38.Card) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Card_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = (this.parent.context.$implicit.usuario.fotoProfile != (null as any));
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_6_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = (this.parent.context.$implicit.usuario.fotoProfile == (null as any));
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_8_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset([]);
        this._Item_2_4._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset([]);
        this._Item_2_4._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.ngAfterContentInit(); }
    }
    const currVal_3:any = import5.interpolate(1,'',this.parent.context.$implicit.usuario.username,'');
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_12,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import5.interpolate(1,'',this.parent.context.$implicit.mensagem,'');
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_15,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.goUsuario(this.parent.context.$implicit.usuario.id)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_NotificacoesPage2(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NotificacoesPage2(viewUtils,parentInjector,declarationEl);
}
class _View_NotificacoesPage3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_NotificacoesPage3,renderType_NotificacoesPage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import5.interpolate(1,'',this.parent.parent.context.$implicit.usuario.fotoProfile,'');
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import36.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NotificacoesPage3(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NotificacoesPage3(viewUtils,parentInjector,declarationEl);
}
class _View_NotificacoesPage4 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_NotificacoesPage4,renderType_NotificacoesPage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'src','http://www.iconsfind.com/wp-content/uploads/2015/11/20151112_5643f331cf8c4.png');
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
}
function viewFactory_NotificacoesPage4(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NotificacoesPage4(viewUtils,parentInjector,declarationEl);
}
class _View_NotificacoesPage5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Item_4_4:import39.Item;
  _ItemContent_4_5:import39.ItemContent;
  _query_Label_4_0:import40.QueryList<any>;
  _query_Button_4_1:import40.QueryList<any>;
  _query_Icon_4_2:import40.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Avatar_6_3:import41.Avatar;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _TemplateRef_8_5:any;
  _NgIf_8_6:import37.NgIf;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _TemplateRef_10_5:any;
  _NgIf_10_6:import37.NgIf;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_NotificacoesPage5,renderType_NotificacoesPage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','modeloItemAgendaItens modeloItemNotificacoesItens');
    this._text_1 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','modeloItemAgenda1');
    this._text_3 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','item item-block');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import42.viewFactory_Item0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Item_4_4 = new import39.Item(this.parent.parent.parentInjector.get(import43.Form),this.parent.parent.parentInjector.get(import22.Config),new import23.ElementRef(this._el_4),this.renderer);
    this._ItemContent_4_5 = new import39.ItemContent();
    this._query_Label_4_0 = new import40.QueryList<any>();
    this._query_Button_4_1 = new import40.QueryList<any>();
    this._query_Icon_4_2 = new import40.QueryList<any>();
    this._appEl_4.initComponent(this._Item_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_6,'item-left','');
    this._Avatar_6_3 = new import41.Avatar();
    this._text_7 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._appEl_8 = new import2.AppElement(8,6,this,this._anchor_8);
    this._TemplateRef_8_5 = new import34.TemplateRef_(this._appEl_8,viewFactory_NotificacoesPage6);
    this._NgIf_8_6 = new import37.NgIf(this._appEl_8.vcRef,this._TemplateRef_8_5);
    this._text_9 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._anchor_10 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._appEl_10 = new import2.AppElement(10,6,this,this._anchor_10);
    this._TemplateRef_10_5 = new import34.TemplateRef_(this._appEl_10,viewFactory_NotificacoesPage7);
    this._NgIf_10_6 = new import37.NgIf(this._appEl_10.vcRef,this._TemplateRef_10_5);
    this._text_11 = this.renderer.createText(this._el_6,'\n          ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n    	      ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'h4',(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n    	      ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n    	  ',(null as any));
    this._query_Label_4_0.reset([]);
    this._Item_4_4.contentLabel = this._query_Label_4_0.first;
    compView_4.create(this._Item_4_4,[
      [].concat([this._el_6]),
      [],
      [].concat([
        this._text_5,
        this._text_12,
        this._el_13,
        this._text_15,
        this._el_16,
        this._text_18,
        this._text_19
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_20 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_2,'div',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n          ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'div',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','modeloItemAgenda-data');
    this._text_24 = this.renderer.createText(this._el_23,'\n            ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'h3',(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'',(null as any));
    this._text_27 = this.renderer.createText(this._el_23,'\n            ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_23,'h4',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'',(null as any));
    this._text_30 = this.renderer.createText(this._el_23,'\n          ',(null as any));
    this._text_31 = this.renderer.createText(this._el_21,'\n\n          ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_21,'div',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','modeloItemAgenda-nomeEvento');
    this._text_33 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_32,'p',(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'',(null as any));
    this._text_36 = this.renderer.createText(this._el_32,'\n          ',(null as any));
    this._text_37 = this.renderer.createText(this._el_21,'\n\n          ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_21,'div',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','modeloItemAgenda-horario');
    this._text_39 = this.renderer.createText(this._el_38,'\n            ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_38,'p',(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'',(null as any));
    this._text_42 = this.renderer.createText(this._el_38,'\n          ',(null as any));
    this._text_43 = this.renderer.createText(this._el_21,'\n      ',(null as any));
    this._text_44 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._text_45 = this.renderer.createText(this._el_0,'\n\n    	',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_21,'click',this.eventHandler(this._handle_click_21_0.bind(this)));
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    this._expr_9 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._anchor_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import37.NgIf) && (8 === requestNodeIndex))) { return this._NgIf_8_6; }
    if (((token === import34.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import37.NgIf) && (10 === requestNodeIndex))) { return this._NgIf_10_6; }
    if (((token === import41.Avatar) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Avatar_6_3; }
    if (((token === import39.Item) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Item_4_4; }
    if (((token === import39.ItemContent) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ItemContent_4_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = (this.parent.context.$implicit.usuario.fotoProfile != (null as any));
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_8_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = (this.parent.context.$implicit.usuario.fotoProfile == (null as any));
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_10_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_1.dirty) {
        this._query_Button_4_1.reset([]);
        this._Item_4_4._buttons = this._query_Button_4_1;
        this._query_Button_4_1.notifyOnChanges();
      }
      if (this._query_Icon_4_2.dirty) {
        this._query_Icon_4_2.reset([]);
        this._Item_4_4._icons = this._query_Icon_4_2;
        this._query_Icon_4_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_4_4.ngAfterContentInit(); }
    }
    const currVal_3:any = import5.interpolate(1,'',this.parent.context.$implicit.usuario.username,'');
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_14,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import5.interpolate(1,'',this.parent.context.$implicit.mensagem,'');
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_17,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = import5.interpolate(1,'',this.parent.context.$implicit.evento.momento.date(),'');
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_26,currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import5.interpolate(1,'',this.parent.context.$implicit.evento.momento.format('dddd'),'');
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_29,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = import5.interpolate(1,'',this.parent.context.$implicit.evento.titulo,'');
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_35,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = import5.interpolate(2,'',this.parent.context.$implicit.evento.hrInicial,' às ',this.parent.context.$implicit.evento.hrFinal,'');
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_41,currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.goUsuario(this.parent.context.$implicit.usuario.id)) !== false);
    return (true && pd_0);
  }
  private _handle_click_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.abrirEvento(this.parent.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_NotificacoesPage5(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NotificacoesPage5(viewUtils,parentInjector,declarationEl);
}
class _View_NotificacoesPage6 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_NotificacoesPage6,renderType_NotificacoesPage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import5.interpolate(1,'',this.parent.parent.context.$implicit.usuario.fotoProfile,'');
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import36.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NotificacoesPage6(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NotificacoesPage6(viewUtils,parentInjector,declarationEl);
}
class _View_NotificacoesPage7 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_NotificacoesPage7,renderType_NotificacoesPage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'src','http://www.iconsfind.com/wp-content/uploads/2015/11/20151112_5643f331cf8c4.png');
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
}
function viewFactory_NotificacoesPage7(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NotificacoesPage7(viewUtils,parentInjector,declarationEl);
}