/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../services/GrupoService';
import * as import4 from './usuario-grupo';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/http/src/http';
import * as import10 from 'ionic-angular/navigation/nav-controller';
import * as import11 from 'ionic-angular/navigation/nav-params';
import * as import12 from 'ionic-angular/components/loading/loading';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from 'ionic-angular/components/toolbar/toolbar';
import * as import16 from 'ionic-angular/components/navbar/navbar';
import * as import17 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import18 from 'ionic-angular/components/content/content';
import * as import19 from 'ionic-angular/components/searchbar/searchbar';
import * as import20 from 'ionic-angular/components/list/list';
import * as import21 from '@angular/common/src/directives/ng_for';
import * as import22 from 'ionic-angular/components/icon/icon';
import * as import23 from 'ionic-angular/config/config';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from 'ionic-angular/navigation/view-controller';
import * as import26 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import29 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import30 from 'ionic-angular/util/keyboard';
import * as import31 from '@angular/core/src/zone/ng_zone';
import * as import32 from 'ionic-angular/components/tabs/tabs';
import * as import33 from '../../node_modules/ionic-angular/components/searchbar/searchbar.ngfactory';
import * as import34 from '@angular/forms/src/directives/ng_control';
import * as import35 from 'ionic-angular/gestures/gesture-controller';
import * as import36 from '@angular/core/src/linker/template_ref';
import * as import37 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import38 from 'ionic-angular/components/item/item';
import * as import39 from '@angular/core/src/linker/query_list';
import * as import40 from 'ionic-angular/components/label/label';
import * as import41 from 'ionic-angular/components/checkbox/checkbox';
import * as import42 from 'ionic-angular/components/avatar/avatar';
import * as import43 from '@angular/common/src/directives/ng_if';
import * as import44 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import45 from 'ionic-angular/util/form';
import * as import46 from '../../node_modules/ionic-angular/components/checkbox/checkbox.ngfactory';
import * as import47 from '@angular/forms/src/directives/control_value_accessor';
import * as import48 from '@angular/core/src/security';
var renderType_UsuarioGrupoPage_Host:import0.RenderComponentType = (null as any);
class _View_UsuarioGrupoPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _GrupoService_0_4:import3.GrupoService;
  _UsuarioGrupoPage_0_5:import4.UsuarioGrupoPage;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_UsuarioGrupoPage_Host0,renderType_UsuarioGrupoPage_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UsuarioGrupoPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._GrupoService_0_4 = new import3.GrupoService(this.parentInjector.get(import9.Http));
    this._UsuarioGrupoPage_0_5 = new import4.UsuarioGrupoPage(this.parentInjector.get(import10.NavController),this.parentInjector.get(import11.NavParams),this._GrupoService_0_4,this.parentInjector.get(import12.LoadingController));
    this._appEl_0.initComponent(this._UsuarioGrupoPage_0_5,[],compView_0);
    compView_0.create(this._UsuarioGrupoPage_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.GrupoService) && (0 === requestNodeIndex))) { return this._GrupoService_0_4; }
    if (((token === import4.UsuarioGrupoPage) && (0 === requestNodeIndex))) { return this._UsuarioGrupoPage_0_5; }
    return notFoundResult;
  }
}
function viewFactory_UsuarioGrupoPage_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_UsuarioGrupoPage_Host === (null as any))) { (renderType_UsuarioGrupoPage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,[],{})); }
  return new _View_UsuarioGrupoPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const UsuarioGrupoPageNgFactory:import14.ComponentFactory<import4.UsuarioGrupoPage> = new import14.ComponentFactory<import4.UsuarioGrupoPage>('ng-component',viewFactory_UsuarioGrupoPage_Host0,import4.UsuarioGrupoPage);
const styles_UsuarioGrupoPage:any[] = [];
var renderType_UsuarioGrupoPage:import0.RenderComponentType = (null as any);
class _View_UsuarioGrupoPage0 extends import1.AppView<import4.UsuarioGrupoPage> {
  _el_0:any;
  _Header_0_3:import15.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import16.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import17.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import18.Content;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _Searchbar_11_4:import19.Searchbar;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _List_19_3:import20.List;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _TemplateRef_21_5:any;
  _NgFor_21_6:import21.NgFor;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _Icon_32_3:import22.Icon;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _Icon_37_3:import22.Icon;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_UsuarioGrupoPage0,renderType_UsuarioGrupoPage,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import15.Header(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import25.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import26.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import16.Navbar(this.parentInjector.get(import27.App),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import10.NavController,(null as any)),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import28.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import17.ToolbarTitle(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import15.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'Adicione membros',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','bg-branco');
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import29.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import18.Content(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import27.App),this.parentInjector.get(import30.Keyboard),this.parentInjector.get(import31.NgZone),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import32.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-searchbar',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','inputBuscaAddMembrosEvento');
    this._appEl_11 = new import2.AppElement(11,9,this,this._el_11);
    var compView_11:any = import33.viewFactory_Searchbar0(this.viewUtils,this.injector(11),this._appEl_11);
    this._Searchbar_11_4 = new import19.Searchbar(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_11),this.renderer,this.parentInjector.get(import34.NgControl,(null as any)));
    this._appEl_11.initComponent(this._Searchbar_11_4,[],compView_11);
    compView_11.create(this._Searchbar_11_4,[],(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'br',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'hr',(null as any));
    this.renderer.setElementAttribute(this._el_15,'id','linhaSeparadora');
    this._text_16 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'br',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_19_3 = new import20.List(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_19),this.renderer,this.parentInjector.get(import35.GestureController));
    this._text_20 = this.renderer.createText(this._el_19,'\n\n    ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._appEl_21 = new import2.AppElement(21,19,this,this._anchor_21);
    this._TemplateRef_21_5 = new import36.TemplateRef_(this._appEl_21,viewFactory_UsuarioGrupoPage1);
    this._NgFor_21_6 = new import21.NgFor(this._appEl_21.vcRef,this._TemplateRef_21_5,this.parentInjector.get(import37.IterableDiffers),this.ref);
    this._text_22 = this.renderer.createText(this._el_19,'\n\n  ',(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','botoesForm');
    this._text_25 = this.renderer.createText(this._el_24,'\n\n    ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','botaoOverlay1');
    this._text_27 = this.renderer.createText(this._el_24,'\n    ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_24,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','botaoOverlay2');
    this._text_29 = this.renderer.createText(this._el_24,'\n\n    ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_24,'a',(null as any));
    this.renderer.setElementAttribute(this._el_30,'href','#');
    this._text_31 = this.renderer.createText(this._el_30,'\n      ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','botaoConfirma');
    this.renderer.setElementAttribute(this._el_32,'name','checkmark-circle');
    this.renderer.setElementAttribute(this._el_32,'role','img');
    this._Icon_32_3 = new import22.Icon(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_32),this.renderer);
    this._text_33 = this.renderer.createText(this._el_30,'\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_24,'\n\n    ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_24,'a',(null as any));
    this.renderer.setElementAttribute(this._el_35,'href','#');
    this._text_36 = this.renderer.createText(this._el_35,'\n      ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','botaoRejeita');
    this.renderer.setElementAttribute(this._el_37,'name','close-circle');
    this.renderer.setElementAttribute(this._el_37,'role','img');
    this._Icon_37_3 = new import22.Icon(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_37),this.renderer);
    this._text_38 = this.renderer.createText(this._el_35,'\n    ',(null as any));
    this._text_39 = this.renderer.createText(this._el_24,'\n\n  ',(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_9.create(this._Content_9_4,[
      [],
      [].concat([
        this._text_10,
        this._el_11,
        this._text_12,
        this._el_13,
        this._text_14,
        this._el_15,
        this._text_16,
        this._el_17,
        this._text_18,
        this._el_19,
        this._text_23,
        this._el_24,
        this._text_40
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_41 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_32,'click',this.eventHandler(this._handle_click_32_0.bind(this)));
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    this._expr_12 = import8.UNINITIALIZED;
    this._expr_13 = import8.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import16.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import15.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import19.Searchbar) && (11 === requestNodeIndex))) { return this._Searchbar_11_4; }
    if (((token === import36.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import21.NgFor) && (21 === requestNodeIndex))) { return this._NgFor_21_6; }
    if (((token === import20.List) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._List_19_3; }
    if (((token === import22.Icon) && (32 === requestNodeIndex))) { return this._Icon_32_3; }
    if (((token === import22.Icon) && (37 === requestNodeIndex))) { return this._Icon_37_3; }
    if (((token === import18.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Searchbar_11_4.ngOnInit(); }
    changes = (null as any);
    const currVal_8:any = this.context.items;
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgFor_21_6.ngForOf = currVal_8;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_8,currVal_8);
      this._expr_8 = currVal_8;
    }
    if ((changes !== (null as any))) { this._NgFor_21_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_21_6.ngDoCheck(); }
    const currVal_10:any = 'checkmark-circle';
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Icon_32_3.name = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_12:any = 'close-circle';
    if (import5.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Icon_37_3.name = currVal_12;
      this._expr_12 = currVal_12;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Searchbar_11_4._value;
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_11,'searchbar-has-value',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._Searchbar_11_4._isActive;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_11,'searchbar-active',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._Searchbar_11_4.showCancelButton;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_11,'searchbar-show-cancel',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._Searchbar_11_4.shouldAlignLeft();
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_11,'searchbar-left-aligned',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Searchbar_11_4._sbHasFocus;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_11,'searchbar-has-focus',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_11:any = this._Icon_32_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_32,'hide',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_13:any = this._Icon_37_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_37,'hide',currVal_13);
      this._expr_13 = currVal_13;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); }
      this._Searchbar_11_4.ngAfterViewChecked();
    }
  }
  destroyInternal():void {
    this._Icon_32_3.ngOnDestroy();
    this._Icon_37_3.ngOnDestroy();
    this._Content_9_4.ngOnDestroy();
  }
  private _handle_click_32_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.salvargrupo()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_UsuarioGrupoPage0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.UsuarioGrupoPage> {
  if ((renderType_UsuarioGrupoPage === (null as any))) { (renderType_UsuarioGrupoPage = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_UsuarioGrupoPage,{})); }
  return new _View_UsuarioGrupoPage0(viewUtils,parentInjector,declarationEl);
}
class _View_UsuarioGrupoPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import38.Item;
  _ItemContent_0_5:import38.ItemContent;
  _query_Label_0_0:import39.QueryList<any>;
  _query_Button_0_1:import39.QueryList<any>;
  _query_Icon_0_2:import39.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Label_2_3:import40.Label;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _Checkbox_5_4:import41.Checkbox;
  __NG_VALUE_ACCESSOR_5_5:any[];
  _text_6:any;
  _el_7:any;
  _Avatar_7_3:import42.Avatar;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _TemplateRef_9_5:any;
  _NgIf_9_6:import43.NgIf;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import43.NgIf;
  _text_12:any;
  _text_13:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_UsuarioGrupoPage1,renderType_UsuarioGrupoPage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  get _NG_VALUE_ACCESSOR_5_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_5_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_5_5 = [this._Checkbox_5_4]); }
    return this.__NG_VALUE_ACCESSOR_5_5;
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import44.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import38.Item(this.parent.parentInjector.get(import45.Form),this.parent.parentInjector.get(import23.Config),new import24.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import38.ItemContent();
    this._query_Label_0_0 = new import39.QueryList<any>();
    this._query_Button_0_1 = new import39.QueryList<any>();
    this._query_Icon_0_2 = new import39.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_2_3 = new import40.Label(this.parent.parentInjector.get(import23.Config),new import24.ElementRef(this._el_2),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-checkbox',(null as any));
    this._appEl_5 = new import2.AppElement(5,0,this,this._el_5);
    var compView_5:any = import46.viewFactory_Checkbox0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Checkbox_5_4 = new import41.Checkbox(this.parent.parentInjector.get(import23.Config),this.parent.parentInjector.get(import45.Form),this._Item_0_4,new import24.ElementRef(this._el_5),this.renderer);
    this._appEl_5.initComponent(this._Checkbox_5_4,[],compView_5);
    compView_5.create(this._Checkbox_5_4,[],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_7,'item-left','');
    this._Avatar_7_3 = new import42.Avatar();
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._appEl_9 = new import2.AppElement(9,7,this,this._anchor_9);
    this._TemplateRef_9_5 = new import36.TemplateRef_(this._appEl_9,viewFactory_UsuarioGrupoPage2);
    this._NgIf_9_6 = new import43.NgIf(this._appEl_9.vcRef,this._TemplateRef_9_5);
    this._text_10 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._appEl_11 = new import2.AppElement(11,7,this,this._anchor_11);
    this._TemplateRef_11_5 = new import36.TemplateRef_(this._appEl_11,viewFactory_UsuarioGrupoPage3);
    this._NgIf_11_6 = new import43.NgIf(this._appEl_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_0_0.reset([this._Label_2_3]);
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      [].concat([
        this._el_5,
        this._el_7
      ]
      ),
      [].concat([this._el_2]),
      [].concat([
        this._text_1,
        this._text_4,
        this._text_6,
        this._text_13
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._text_13
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import40.Label) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Label_2_3; }
    if (((token === import41.Checkbox) && (5 === requestNodeIndex))) { return this._Checkbox_5_4; }
    if (((token === import47.NG_VALUE_ACCESSOR) && (5 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_5_5; }
    if (((token === import36.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import43.NgIf) && (9 === requestNodeIndex))) { return this._NgIf_9_6; }
    if (((token === import36.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import43.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6; }
    if (((token === import42.Avatar) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Avatar_7_3; }
    if (((token === import38.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Item_0_4; }
    if (((token === import38.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ItemContent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = import5.interpolate(1,'',this.context.$implicit.checked,'');
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Checkbox_5_4.checked = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = (this.context.$implicit.fotoProfile != (null as any));
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_9_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = (this.context.$implicit.fotoProfile == (null as any));
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_11_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset([]);
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Checkbox_5_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_0:any = import5.interpolate(1,'',this.context.$implicit.username,'');
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_4:any = this._Checkbox_5_4._disabled;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_5,'checkbox-disabled',currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Checkbox_5_4.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this._appEl_5.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.change(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._Checkbox_5_4._click($event)) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_UsuarioGrupoPage1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UsuarioGrupoPage1(viewUtils,parentInjector,declarationEl);
}
class _View_UsuarioGrupoPage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_UsuarioGrupoPage2,renderType_UsuarioGrupoPage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import5.interpolate(1,'',this.parent.context.$implicit.fotoProfile,'');
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import48.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UsuarioGrupoPage2(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UsuarioGrupoPage2(viewUtils,parentInjector,declarationEl);
}
class _View_UsuarioGrupoPage3 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_UsuarioGrupoPage3,renderType_UsuarioGrupoPage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'src','http://www.iconsfind.com/wp-content/uploads/2015/11/20151112_5643f331cf8c4.png');
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
}
function viewFactory_UsuarioGrupoPage3(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UsuarioGrupoPage3(viewUtils,parentInjector,declarationEl);
}