/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../services/UsuarioService';
import * as import4 from '../../services/user-data';
import * as import5 from './agenda';
import * as import6 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/di/injector';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/change_detection';
import * as import10 from '@angular/http/src/http';
import * as import11 from 'ionic-angular/util/events';
import * as import12 from '@ionic/storage/es2015/storage';
import * as import13 from 'ionic-angular/navigation/nav-controller';
import * as import14 from 'ionic-angular/navigation/nav-params';
import * as import15 from '@angular/core/src/metadata/view';
import * as import16 from '@angular/core/src/linker/component_factory';
import * as import17 from 'ionic-angular/components/toolbar/toolbar';
import * as import18 from 'ionic-angular/components/navbar/navbar';
import * as import19 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import20 from '@angular/forms/src/directives/ng_model';
import * as import21 from '@angular/forms/src/directives/ng_control_status';
import * as import22 from 'ionic-angular/components/segment/segment';
import * as import23 from '@angular/core/src/linker/query_list';
import * as import24 from 'ionic-angular/components/content/content';
import * as import25 from 'ionic-angular/components/refresher/refresher';
import * as import26 from 'ionic-angular/components/refresher/refresher-content';
import * as import27 from '@angular/common/src/directives/ng_switch';
import * as import28 from 'ionic-angular/config/config';
import * as import29 from '@angular/core/src/linker/element_ref';
import * as import30 from 'ionic-angular/navigation/view-controller';
import * as import31 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import32 from 'ionic-angular/components/app/app';
import * as import33 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import34 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import35 from '../../node_modules/ionic-angular/components/segment/segment.ngfactory';
import * as import36 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import37 from 'ionic-angular/util/keyboard';
import * as import38 from '@angular/core/src/zone/ng_zone';
import * as import39 from 'ionic-angular/components/tabs/tabs';
import * as import40 from 'ionic-angular/gestures/gesture-controller';
import * as import41 from '../../node_modules/ionic-angular/components/refresher/refresher-content.ngfactory';
import * as import42 from '@angular/core/src/linker/template_ref';
import * as import43 from '@angular/forms/src/directives/ng_control';
import * as import44 from '@angular/core/src/security';
import * as import45 from 'ionic-angular/components/grid/grid';
import * as import46 from 'ionic-angular/components/button/button';
import * as import47 from 'ionic-angular/components/icon/icon';
import * as import48 from '@angular/common/src/directives/ng_for';
import * as import49 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import50 from '@angular/core/src/change_detection/differs/iterable_differs';
var renderType_AgendaPage_Host:import0.RenderComponentType = (null as any);
class _View_AgendaPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UsuarioService_0_4:import3.UsuarioService;
  _UserData_0_5:import4.UserData;
  _AgendaPage_0_6:import5.AgendaPage;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_AgendaPage_Host0,renderType_AgendaPage_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AgendaPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UsuarioService_0_4 = new import3.UsuarioService(this.parentInjector.get(import10.Http));
    this._UserData_0_5 = new import4.UserData(this.parentInjector.get(import11.Events),this.parentInjector.get(import12.Storage));
    this._AgendaPage_0_6 = new import5.AgendaPage(this.parentInjector.get(import13.NavController),this._UsuarioService_0_4,this.parentInjector.get(import14.NavParams),this._UserData_0_5);
    this._appEl_0.initComponent(this._AgendaPage_0_6,[],compView_0);
    compView_0.create(this._AgendaPage_0_6,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.UsuarioService) && (0 === requestNodeIndex))) { return this._UsuarioService_0_4; }
    if (((token === import4.UserData) && (0 === requestNodeIndex))) { return this._UserData_0_5; }
    if (((token === import5.AgendaPage) && (0 === requestNodeIndex))) { return this._AgendaPage_0_6; }
    return notFoundResult;
  }
}
function viewFactory_AgendaPage_Host0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_AgendaPage_Host === (null as any))) { (renderType_AgendaPage_Host = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,[],{})); }
  return new _View_AgendaPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const AgendaPageNgFactory:import16.ComponentFactory<import5.AgendaPage> = new import16.ComponentFactory<import5.AgendaPage>('ng-component',viewFactory_AgendaPage_Host0,import5.AgendaPage);
const styles_AgendaPage:any[] = [];
var renderType_AgendaPage:import0.RenderComponentType = (null as any);
class _View_AgendaPage0 extends import1.AppView<import5.AgendaPage> {
  _el_0:any;
  _Header_0_3:import17.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import18.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import19.ToolbarTitle;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _Toolbar_10_4:import17.Toolbar;
  _text_11:any;
  _el_12:any;
  _NgModel_12_3:import20.NgModel;
  _NgControl_12_4:any;
  _NgControlStatus_12_5:import21.NgControlStatus;
  _Segment_12_6:import22.Segment;
  _query_SegmentButton_12_0:import23.QueryList<any>;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _SegmentButton_14_4:import22.SegmentButton;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _SegmentButton_17_4:import22.SegmentButton;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _SegmentButton_20_4:import22.SegmentButton;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _Content_26_4:import24.Content;
  _text_27:any;
  _el_28:any;
  _Refresher_28_3:import25.Refresher;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _RefresherContent_30_4:import26.RefresherContent;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _NgSwitch_33_3:import27.NgSwitch;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _appEl_35:import2.AppElement;
  _TemplateRef_35_5:any;
  _NgSwitchCase_35_6:import27.NgSwitchCase;
  _text_36:any;
  _anchor_37:any;
  /*private*/ _appEl_37:import2.AppElement;
  _TemplateRef_37_5:any;
  _NgSwitchCase_37_6:import27.NgSwitchCase;
  _text_38:any;
  _anchor_39:any;
  /*private*/ _appEl_39:import2.AppElement;
  _TemplateRef_39_5:any;
  _NgSwitchCase_39_6:import27.NgSwitchCase;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_AgendaPage0,renderType_AgendaPage,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import17.Header(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import30.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import31.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import18.Navbar(this.parentInjector.get(import32.App),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import13.NavController,(null as any)),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import33.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import19.ToolbarTitle(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import17.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','img-logo');
    this.renderer.setElementAttribute(this._el_6,'src','assets/img/logo.png');
    this.renderer.setElementAttribute(this._el_6,'width','55%');
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._ToolbarTitle_4_4,[[].concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_8
      ]
      )
    ]
    ,(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_0,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','toolbar');
    this.renderer.setElementAttribute(this._el_10,'no-border-top','');
    this._appEl_10 = new import2.AppElement(10,0,this,this._el_10);
    var compView_10:any = import34.viewFactory_Toolbar0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Toolbar_10_4 = new import17.Toolbar(this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_10),this.renderer);
    this._appEl_10.initComponent(this._Toolbar_10_4,[],compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-segment',(null as any));
    this._NgModel_12_3 = new import20.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_12_4 = this._NgModel_12_3;
    this._NgControlStatus_12_5 = new import21.NgControlStatus(this._NgControl_12_4);
    this._Segment_12_6 = new import22.Segment(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_12),this.renderer,this._NgControl_12_4);
    this._query_SegmentButton_12_0 = new import23.QueryList<any>();
    this._text_13 = this.renderer.createText(this._el_12,'\n      ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','segment-button');
    this.renderer.setElementAttribute(this._el_14,'role','button');
    this.renderer.setElementAttribute(this._el_14,'tappable','');
    this.renderer.setElementAttribute(this._el_14,'value','agenda');
    this._appEl_14 = new import2.AppElement(14,12,this,this._el_14);
    var compView_14:any = import35.viewFactory_SegmentButton0(this.viewUtils,this.injector(14),this._appEl_14);
    this._SegmentButton_14_4 = new import22.SegmentButton(this.renderer,new import29.ElementRef(this._el_14));
    this._appEl_14.initComponent(this._SegmentButton_14_4,[],compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n        Agenda\n      ',(null as any));
    compView_14.create(this._SegmentButton_14_4,[[].concat([this._text_15])],(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n      ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_12,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','segment-button');
    this.renderer.setElementAttribute(this._el_17,'role','button');
    this.renderer.setElementAttribute(this._el_17,'tappable','');
    this.renderer.setElementAttribute(this._el_17,'value','meusEventos');
    this._appEl_17 = new import2.AppElement(17,12,this,this._el_17);
    var compView_17:any = import35.viewFactory_SegmentButton0(this.viewUtils,this.injector(17),this._appEl_17);
    this._SegmentButton_17_4 = new import22.SegmentButton(this.renderer,new import29.ElementRef(this._el_17));
    this._appEl_17.initComponent(this._SegmentButton_17_4,[],compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n        Meus Eventos\n      ',(null as any));
    compView_17.create(this._SegmentButton_17_4,[[].concat([this._text_18])],(null as any));
    this._text_19 = this.renderer.createText(this._el_12,'\n      ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_12,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','segment-button');
    this.renderer.setElementAttribute(this._el_20,'role','button');
    this.renderer.setElementAttribute(this._el_20,'tappable','');
    this.renderer.setElementAttribute(this._el_20,'value','convites');
    this._appEl_20 = new import2.AppElement(20,12,this,this._el_20);
    var compView_20:any = import35.viewFactory_SegmentButton0(this.viewUtils,this.injector(20),this._appEl_20);
    this._SegmentButton_20_4 = new import22.SegmentButton(this.renderer,new import29.ElementRef(this._el_20));
    this._appEl_20.initComponent(this._SegmentButton_20_4,[],compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n        Convites\n      ',(null as any));
    compView_20.create(this._SegmentButton_20_4,[[].concat([this._text_21])],(null as any));
    this._text_22 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_10.create(this._Toolbar_10_4,[
      [],
      [],
      [],
      [].concat([
        this._text_11,
        this._el_12,
        this._text_23
      ]
      )
    ]
    ,(null as any));
    this._text_24 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_25 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_26 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','bg-branco');
    this._appEl_26 = new import2.AppElement(26,(null as any),this,this._el_26);
    var compView_26:any = import36.viewFactory_Content0(this.viewUtils,this.injector(26),this._appEl_26);
    this._Content_26_4 = new import24.Content(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_26),this.renderer,this.parentInjector.get(import32.App),this.parentInjector.get(import37.Keyboard),this.parentInjector.get(import38.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import39.Tabs,(null as any)));
    this._appEl_26.initComponent(this._Content_26_4,[],compView_26);
    this._text_27 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'ion-refresher',(null as any));
    this._Refresher_28_3 = new import25.Refresher(this._Content_26_4,this.parentInjector.get(import38.NgZone),this.parentInjector.get(import40.GestureController));
    this._text_29 = this.renderer.createText(this._el_28,'\n    ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'ion-refresher-content',(null as any));
    this._appEl_30 = new import2.AppElement(30,28,this,this._el_30);
    var compView_30:any = import41.viewFactory_RefresherContent0(this.viewUtils,this.injector(30),this._appEl_30);
    this._RefresherContent_30_4 = new import26.RefresherContent(this._Refresher_28_3,this.parentInjector.get(import28.Config));
    this._appEl_30.initComponent(this._RefresherContent_30_4,[],compView_30);
    compView_30.create(this._RefresherContent_30_4,[],(null as any));
    this._text_31 = this.renderer.createText(this._el_28,'\n  ',(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n\n\n  ',(null as any));
    this._el_33 = this.renderer.createElement((null as any),'div',(null as any));
    this._NgSwitch_33_3 = new import27.NgSwitch();
    this._text_34 = this.renderer.createText(this._el_33,'\n    ',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor(this._el_33,(null as any));
    this._appEl_35 = new import2.AppElement(35,33,this,this._anchor_35);
    this._TemplateRef_35_5 = new import42.TemplateRef_(this._appEl_35,viewFactory_AgendaPage1);
    this._NgSwitchCase_35_6 = new import27.NgSwitchCase(this._appEl_35.vcRef,this._TemplateRef_35_5,this._NgSwitch_33_3);
    this._text_36 = this.renderer.createText(this._el_33,'\n\n    ',(null as any));
    this._anchor_37 = this.renderer.createTemplateAnchor(this._el_33,(null as any));
    this._appEl_37 = new import2.AppElement(37,33,this,this._anchor_37);
    this._TemplateRef_37_5 = new import42.TemplateRef_(this._appEl_37,viewFactory_AgendaPage3);
    this._NgSwitchCase_37_6 = new import27.NgSwitchCase(this._appEl_37.vcRef,this._TemplateRef_37_5,this._NgSwitch_33_3);
    this._text_38 = this.renderer.createText(this._el_33,'\n\n    ',(null as any));
    this._anchor_39 = this.renderer.createTemplateAnchor(this._el_33,(null as any));
    this._appEl_39 = new import2.AppElement(39,33,this,this._anchor_39);
    this._TemplateRef_39_5 = new import42.TemplateRef_(this._appEl_39,viewFactory_AgendaPage5);
    this._NgSwitchCase_39_6 = new import27.NgSwitchCase(this._appEl_39.vcRef,this._TemplateRef_39_5,this._NgSwitch_33_3);
    this._text_40 = this.renderer.createText(this._el_33,'\n\n  ',(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n',(null as any));
    this._text_42 = this.renderer.createText((null as any),'\n\n\n\n\n',(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_26.create(this._Content_26_4,[
      [],
      [].concat([
        this._text_27,
        this._text_32,
        this._el_33,
        this._text_41,
        this._text_42,
        this._text_43
      ]
      ),
      [].concat([this._el_28])
    ]
    ,(null as any));
    this._text_44 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import9.UNINITIALIZED;
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_12,'ngModelChange',this.eventHandler(this._handle_ngModelChange_12_0.bind(this)));
    this._expr_4 = import9.UNINITIALIZED;
    const subscription_0:any = this._NgModel_12_3.update.subscribe(this.eventHandler(this._handle_ngModelChange_12_0.bind(this)));
    this._expr_5 = import9.UNINITIALIZED;
    this._expr_6 = import9.UNINITIALIZED;
    this._expr_7 = import9.UNINITIALIZED;
    this._expr_8 = import9.UNINITIALIZED;
    this._expr_9 = import9.UNINITIALIZED;
    this._expr_10 = import9.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_14,'click',this.eventHandler(this._handle_click_14_0.bind(this)));
    this._expr_12 = import9.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_17,'click',this.eventHandler(this._handle_click_17_0.bind(this)));
    this._expr_14 = import9.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_20,'click',this.eventHandler(this._handle_click_20_0.bind(this)));
    this._expr_16 = import9.UNINITIALIZED;
    this._expr_17 = import9.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_28,'ionRefresh',this.eventHandler(this._handle_ionRefresh_28_0.bind(this)));
    this._expr_19 = import9.UNINITIALIZED;
    this._expr_20 = import9.UNINITIALIZED;
    const subscription_1:any = this._Refresher_28_3.ionRefresh.subscribe(this.eventHandler(this._handle_ionRefresh_28_0.bind(this)));
    this._expr_21 = import9.UNINITIALIZED;
    this._expr_22 = import9.UNINITIALIZED;
    this._expr_23 = import9.UNINITIALIZED;
    this._expr_24 = import9.UNINITIALIZED;
    this._expr_25 = import9.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._anchor_35,
      this._text_36,
      this._anchor_37,
      this._text_38,
      this._anchor_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarTitle_4_4; }
    if (((token === import18.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Navbar_2_4; }
    if (((token === import22.SegmentButton) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._SegmentButton_14_4; }
    if (((token === import22.SegmentButton) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._SegmentButton_17_4; }
    if (((token === import22.SegmentButton) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._SegmentButton_20_4; }
    if (((token === import20.NgModel) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._NgModel_12_3; }
    if (((token === import43.NgControl) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._NgControl_12_4; }
    if (((token === import21.NgControlStatus) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._NgControlStatus_12_5; }
    if (((token === import22.Segment) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Segment_12_6; }
    if (((token === import17.Toolbar) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Toolbar_10_4; }
    if (((token === import17.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Header_0_3; }
    if (((token === import26.RefresherContent) && (30 === requestNodeIndex))) { return this._RefresherContent_30_4; }
    if (((token === import25.Refresher) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Refresher_28_3; }
    if (((token === import42.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import27.NgSwitchCase) && (35 === requestNodeIndex))) { return this._NgSwitchCase_35_6; }
    if (((token === import42.TemplateRef) && (37 === requestNodeIndex))) { return this._TemplateRef_37_5; }
    if (((token === import27.NgSwitchCase) && (37 === requestNodeIndex))) { return this._NgSwitchCase_37_6; }
    if (((token === import42.TemplateRef) && (39 === requestNodeIndex))) { return this._TemplateRef_39_5; }
    if (((token === import27.NgSwitchCase) && (39 === requestNodeIndex))) { return this._NgSwitchCase_39_6; }
    if (((token === import27.NgSwitch) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._NgSwitch_33_3; }
    if (((token === import24.Content) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Content_26_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import9.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_4:any = this.context.calendario;
    if (import6.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgModel_12_3.model = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import9.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgModel_12_3.ngOnChanges(changes); }
    const currVal_12:any = 'agenda';
    if (import6.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._SegmentButton_14_4.value = currVal_12;
      this._expr_12 = currVal_12;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_14_4.ngOnInit(); }
    const currVal_14:any = 'meusEventos';
    if (import6.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._SegmentButton_17_4.value = currVal_14;
      this._expr_14 = currVal_14;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_17_4.ngOnInit(); }
    const currVal_16:any = 'convites';
    if (import6.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._SegmentButton_20_4.value = currVal_16;
      this._expr_16 = currVal_16;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_20_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_26_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Refresher_28_3.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RefresherContent_30_4.ngOnInit(); }
    const currVal_22:any = this.context.calendario;
    if (import6.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._NgSwitch_33_3.ngSwitch = currVal_22;
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = 'agenda';
    if (import6.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._NgSwitchCase_35_6.ngSwitchCase = currVal_23;
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = 'meusEventos';
    if (import6.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._NgSwitchCase_37_6.ngSwitchCase = currVal_24;
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = 'convites';
    if (import6.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._NgSwitchCase_39_6.ngSwitchCase = currVal_25;
      this._expr_25 = currVal_25;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if (this._query_SegmentButton_12_0.dirty) {
      this._query_SegmentButton_12_0.reset([
        this._SegmentButton_14_4,
        this._SegmentButton_17_4,
        this._SegmentButton_20_4
      ]
      );
      this._Segment_12_6._buttons = this._query_SegmentButton_12_0;
      this._query_SegmentButton_12_0.notifyOnChanges();
    } }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import6.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Toolbar_10_4._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._NgControlStatus_12_5.ngClassUntouched;
    if (import6.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_12,'ng-untouched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_12_5.ngClassTouched;
    if (import6.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_12,'ng-touched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_12_5.ngClassPristine;
    if (import6.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_12,'ng-pristine',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_12_5.ngClassDirty;
    if (import6.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_12,'ng-dirty',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_12_5.ngClassValid;
    if (import6.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_12,'ng-valid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_12_5.ngClassInvalid;
    if (import6.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_12,'ng-invalid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_17:any = this._Content_26_4._sbPadding;
    if (import6.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_26,'statusbar-padding',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_19:any = (this._Refresher_28_3.state !== 'inactive');
    if (import6.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_28,'refresher-active',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._Refresher_28_3._top;
    if (import6.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementStyle(this._el_28,'top',((this.viewUtils.sanitizer.sanitize(import44.SecurityContext.STYLE,currVal_20) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import44.SecurityContext.STYLE,currVal_20).toString()));
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._RefresherContent_30_4.r.state;
    if (import6.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementAttribute(this._el_30,'state',((currVal_21 == (null as any))? (null as any): currVal_21.toString()));
      this._expr_21 = currVal_21;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Segment_12_6.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._NgModel_12_3.ngOnDestroy();
    this._Refresher_28_3.ngOnDestroy();
    this._Content_26_4.ngOnDestroy();
  }
  private _handle_ngModelChange_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.calendario = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_14_0($event:any):boolean {
    this._appEl_14.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_14_4.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_17_0($event:any):boolean {
    this._appEl_17.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_17_4.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_20_0($event:any):boolean {
    this._appEl_20.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_20_4.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_ionRefresh_28_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doRefresh($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AgendaPage0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<import5.AgendaPage> {
  if ((renderType_AgendaPage === (null as any))) { (renderType_AgendaPage = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,styles_AgendaPage,{})); }
  return new _View_AgendaPage0(viewUtils,parentInjector,declarationEl);
}
class _View_AgendaPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _Grid_2_3:import45.Grid;
  _text_3:any;
  _el_4:any;
  _Row_4_3:import45.Row;
  _text_5:any;
  _el_6:any;
  _Col_6_3:import45.Col;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _Button_8_4:import46.Button;
  _text_9:any;
  _el_10:any;
  _Icon_10_3:import47.Icon;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _TemplateRef_18_5:any;
  _NgFor_18_6:import48.NgFor;
  _text_19:any;
  _text_20:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_AgendaPage1,renderType_AgendaPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n    \n\n\n\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-grid',(null as any));
    this._Grid_2_3 = new import45.Grid();
    this._text_3 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-row',(null as any));
    this._Row_4_3 = new import45.Row();
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'ion-col',(null as any));
    this._Col_6_3 = new import45.Col();
    this._text_7 = this.renderer.createText(this._el_6,'\n              ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'button',(null as any));
    this.renderer.setElementAttribute(this._el_8,'clear','');
    this.renderer.setElementAttribute(this._el_8,'ion-button','');
    this._appEl_8 = new import2.AppElement(8,6,this,this._el_8);
    var compView_8:any = import49.viewFactory_Button0(this.viewUtils,this.injector(8),this._appEl_8);
    this._Button_8_4 = new import46.Button((null as any),'',this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_8),this.renderer);
    this._appEl_8.initComponent(this._Button_8_4,[],compView_8);
    this._text_9 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_10,'name','add-circle');
    this.renderer.setElementAttribute(this._el_10,'role','img');
    this.renderer.setElementAttribute(this._el_10,'style','color: #081522; font-size: 40px; padding-left: 0px;');
    this._Icon_10_3 = new import47.Icon(this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_10),this.renderer);
    this._text_11 = this.renderer.createText((null as any),'\n              ',(null as any));
      compView_8.create(this._Button_8_4,[[].concat([
        this._text_9,
        this._el_10,
        this._text_11
      ]
    )],(null as any));
    this._text_12 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_13 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'style','padding-left: 5px; padding-right: 5px;');
    this._text_17 = this.renderer.createText(this._el_16,'\n\n            ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_16,(null as any));
    this._appEl_18 = new import2.AppElement(18,16,this,this._anchor_18);
    this._TemplateRef_18_5 = new import42.TemplateRef_(this._appEl_18,viewFactory_AgendaPage2);
    this._NgFor_18_6 = new import48.NgFor(this._appEl_18.vcRef,this._TemplateRef_18_5,this.parent.parentInjector.get(import50.IterableDiffers),this.parent.ref);
    this._text_19 = this.renderer.createText(this._el_16,'\n      ',(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    this._expr_3 = import9.UNINITIALIZED;
    this._expr_4 = import9.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._text_20
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import47.Icon) && (10 === requestNodeIndex))) { return this._Icon_10_3; }
    if (((token === import46.Button) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Button_8_4; }
    if (((token === import45.Col) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Col_6_3; }
    if (((token === import45.Row) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Row_4_3; }
    if (((token === import45.Grid) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Grid_2_3; }
    if (((token === import42.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import48.NgFor) && (18 === requestNodeIndex))) { return this._NgFor_18_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import9.SimpleChange} = (null as any);
    changed = false;
    const currVal_1:any = '';
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_8_4.clear = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    if (changed) { this._appEl_8.componentView.markAsCheckOnce(); }
    const currVal_2:any = 'add-circle';
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Icon_10_3.name = currVal_2;
      this._expr_2 = currVal_2;
    }
    changes = (null as any);
    const currVal_4:any = this.parent.context.listaEventos;
    if (import6.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgFor_18_6.ngForOf = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import9.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgFor_18_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_18_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_8_4.ngAfterContentInit(); } }
    const currVal_3:any = this._Icon_10_3._hidden;
    if (import6.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_10,'hide',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_10_3.ngOnDestroy();
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.cadastrarEvento()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_AgendaPage1(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AgendaPage1(viewUtils,parentInjector,declarationEl);
}
class _View_AgendaPage2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_AgendaPage2,renderType_AgendaPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n              ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','modeloItemAgenda1');
    this._text_3 = this.renderer.createText(this._el_2,'\n\n                ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','modeloItemAgenda-data');
    this._text_5 = this.renderer.createText(this._el_4,'\n                  ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n                  ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'h4',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n\n                ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','modeloItemAgenda-nomeEvento');
    this._text_14 = this.renderer.createText(this._el_13,'\n                  ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'p',(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n\n                ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','modeloItemAgenda-horario');
    this._text_20 = this.renderer.createText(this._el_19,'\n                  ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'p',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'\n                ',(null as any));
    this._text_24 = this.renderer.createText(this._el_2,'\n\n              ',(null as any));
    this._text_25 = this.renderer.createText(this._el_0,'\n\n            ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    this._expr_3 = import9.UNINITIALIZED;
    this._expr_4 = import9.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import6.interpolate(1,'',this.context.$implicit.evento.momento.date(),'');
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_7,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import6.interpolate(1,'',this.context.$implicit.evento.momento.format('dddd'),'');
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_10,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import6.interpolate(1,'',this.context.$implicit.evento.titulo,'');
    if (import6.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_16,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import6.interpolate(2,'',this.context.$implicit.evento.hrInicial,' às ',this.context.$implicit.evento.hrFinal,'');
    if (import6.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_22,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.abrirEvento(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_AgendaPage2(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AgendaPage2(viewUtils,parentInjector,declarationEl);
}
class _View_AgendaPage3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import48.NgFor;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_AgendaPage3,renderType_AgendaPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import42.TemplateRef_(this._appEl_2,viewFactory_AgendaPage4);
    this._NgFor_2_6 = new import48.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parentInjector.get(import50.IterableDiffers),this.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._expr_0 = import9.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import42.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import48.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import9.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.meusEventos;
    if (import6.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_2_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import9.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AgendaPage3(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AgendaPage3(viewUtils,parentInjector,declarationEl);
}
class _View_AgendaPage4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_AgendaPage4,renderType_AgendaPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','modeloItemAgenda1');
    this._text_3 = this.renderer.createText(this._el_2,'\n\n          ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','modeloItemAgenda-data');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'h4',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n\n          ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','modeloItemAgenda-nomeEvento');
    this._text_14 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'p',(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n          ',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n\n          ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','modeloItemAgenda-horario');
    this._text_20 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'p',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'\n          ',(null as any));
    this._text_24 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    this._expr_3 = import9.UNINITIALIZED;
    this._expr_4 = import9.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import6.interpolate(1,'',this.context.$implicit.evento.momento.date(),'');
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_7,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import6.interpolate(1,'',this.context.$implicit.evento.momento.format('dddd'),'');
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_10,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import6.interpolate(1,'',this.context.$implicit.evento.titulo,'');
    if (import6.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_16,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import6.interpolate(2,'',this.context.$implicit.evento.hrInicial,' às ',this.context.$implicit.evento.hrFinal,'');
    if (import6.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_22,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.abrirEvento(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_AgendaPage4(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AgendaPage4(viewUtils,parentInjector,declarationEl);
}
class _View_AgendaPage5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import48.NgFor;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_AgendaPage5,renderType_AgendaPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import42.TemplateRef_(this._appEl_2,viewFactory_AgendaPage6);
    this._NgFor_2_6 = new import48.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parentInjector.get(import50.IterableDiffers),this.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._expr_0 = import9.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import42.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import48.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import9.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.convitesEvento;
    if (import6.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_2_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import9.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AgendaPage5(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AgendaPage5(viewUtils,parentInjector,declarationEl);
}
class _View_AgendaPage6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement) {
    super(_View_AgendaPage6,renderType_AgendaPage,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','modeloItemAgenda1');
    this._text_3 = this.renderer.createText(this._el_2,'\n\n          ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','modeloItemAgenda-data');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'h4',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n\n          ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','modeloItemAgenda-nomeEvento');
    this._text_14 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'p',(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n          ',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n\n          ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','modeloItemAgenda-horario');
    this._text_20 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'p',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'\n          ',(null as any));
    this._text_24 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    this._expr_3 = import9.UNINITIALIZED;
    this._expr_4 = import9.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import6.interpolate(1,'',this.context.$implicit.evento.momento.date(),'');
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_7,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import6.interpolate(1,'',this.context.$implicit.evento.momento.format('dddd'),'');
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_10,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import6.interpolate(1,'',this.context.$implicit.evento.titulo,'');
    if (import6.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_16,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import6.interpolate(2,'',this.context.$implicit.evento.hrInicial,' às ',this.context.$implicit.evento.hrFinal,'');
    if (import6.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_22,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.abrirEvento(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_AgendaPage6(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AgendaPage6(viewUtils,parentInjector,declarationEl);
}